(function() {
  var subject = "We need you!";
  var bd =
    "Shame on you.  %0D%0A %0D%0A This country was first stolen from the Native Americans and then built on the backs of slaves and is now built on the backs of working class people of all colors and backgrounds, with people of color, women, the LGBTQ community and those with disability suffering the most. How dare you do what you do. We are all immigrants, isn't your family?  %0D%0A %0D%0A The acting director of Immigration and Customs Enforcement said Monday that comparing ICE agents to Nazis is unfair, because 'they’re simply enforcing laws enacted by Congress'.  %0D%0A %0D%0A Thomas Homan employed the 'Nuremberg defense' – used by German Nazi officials in an attempt to escape accountability with the claim they were merely following orders.%0D%0A %0D%0A Stop this atrocity now. ";
  var bd2 =
    "Shame on you, NAME.  %0D%0A %0D%0A This country was first stolen from the Native Americans and then built on the backs of slaves and is now built on the backs of working class people of all colors and backgrounds, with people of color, women, the LGBTQ community and those with disability suffering the most. How dare you do what you do. We are all immigrants, isn't your family?  %0D%0A %0D%0A The acting director of Immigration and Customs Enforcement said Monday that comparing ICE agents to Nazis is unfair, because 'they’re simply enforcing laws enacted by Congress'.  %0D%0A %0D%0A Thomas Homan employed the 'Nuremberg defense' – used by German Nazi officials in an attempt to escape accountability with the claim they were merely following orders.%0D%0A %0D%0A Stop this atrocity now. ";
  var emails = _.shuffle([
    ["Euna Song", "Euna.Song@ice.dhs.org"],
    ["Douglas Ruszcyk", "Douglas.Ruszcyk@ice.dhs.org"],
    ["Byron J.", "Byron.J@ice.dhs.org"],
    ["Jason Brazie", "Jason.Brazie@ice.dhs.org"],
    ["Joseph Reuter", "Joseph.Reuter@ice.dhs.org"],
    ["Nate Fontaine, MSM", "Nate.Fontaine@ice.dhs.org"],
    ["Kevin Tyrrell", "Kevin.Tyrrell@ice.dhs.org"],
    ["Michal Grygo", "Michal.Grygo@ice.dhs.org"],
    ["Christopher Tafe", "Christopher.Tafe@ice.dhs.org"],
    ["Robert Gil", "Robert.Gil@ice.dhs.org"],
    ["Abu Saleh", "Abu.Saleh@ice.dhs.org"],
    ["Sharon Peyus", "Sharon.Peyus@ice.dhs.org"],
    ["David Sayles", "David.Sayles@ice.dhs.org"],
    ["Samuel Padilla", "Samuel.Padilla@ice.dhs.org"],
    ["Stacy Wiechec", "Stacy.Wiechec@ice.dhs.org"],
    ["Mark Lenox", "Mark.Lenox@ice.dhs.org"],
    ["Robert J. Nieves, Jr.", "Robert.J.Nieves@ice.dhs.org"],
    ["Larry Orton", "Larry.Orton@ice.dhs.org"],
    ["Marco Suarez", "Marco.Suarez@ice.dhs.org"],
    ["Sean Willman", "Sean.Willman@ice.dhs.org"],
    ["Reba McGinnis", "Reba.McGinnis@ice.dhs.org"],
    ["Rob Patterson", "Rob.Patterson@ice.dhs.org"],
    ["Terence Glover", "Terence.Glover@ice.dhs.org"],
    ["Edward Bradstreet, CFCE-EnCE", "Edward.Bradstreet@ice.dhs.org"],
    ["John Czerapowicz", "John.Czerapowicz@ice.dhs.org"],
    ["Kevin Coleman", "Kevin.Coleman@ice.dhs.org"],
    ["Maria P. Sickels, PhDc", "Maria.P.Sickels@ice.dhs.org"],
    ["Craig Nadler", "Craig.Nadler@ice.dhs.org"],
    ["Joey Bozik", "Joey.Bozik@ice.dhs.org"],
    ["Justin Leone", "Justin.Leone@ice.dhs.org"],
    ["Shareef Smith", "Shareef.Smith@ice.dhs.org"],
    ["Rose Arenas", "Rose.Arenas@ice.dhs.org"],
    ["Marshall Kennedy", "Marshall.Kennedy@ice.dhs.org"],
    ["Nicholas Volpicella", "Nicholas.Volpicella@ice.dhs.org"],
    ["Raymond Smith", "Raymond.Smith@ice.dhs.org"],
    ["Paul Cotcher", "Paul.Cotcher@ice.dhs.org"],
    ["Deyon Washington", "Deyon.Washington@ice.dhs.org"],
    ["Agnes Hughes", "Agnes.Hughes@ice.dhs.org"],
    ["George Rodriguez", "George.Rodriguez@ice.dhs.org"],
    ["Keith Acosta", "Keith.Acosta@ice.dhs.org"],
    ["Tom Betts", "Tom.Betts@ice.dhs.org"],
    ["Mark Mendoza", "Mark.Mendoza@ice.dhs.org"],
    ["Devon Haskins", "Devon.Haskins@ice.dhs.org"],
    ["Eric Bowers", "Eric.Bowers@ice.dhs.org"],
    ["Harry Burns", "Harry.Burns@ice.dhs.org"],
    ["Albert Rabadi", "Albert.Rabadi@ice.dhs.org"],
    ["Joel N.", "Joel.N@ice.dhs.org"],
    ["Eric Munson", "Eric.Munson@ice.dhs.org"],
    ["Craig Coleman", "Craig.Coleman@ice.dhs.org"],
    ["Edward Mederos", "Edward.Mederos@ice.dhs.org"],
    ["Derrick Perry", "Derrick.Perry@ice.dhs.org"],
    ["Jeff Barczak", "Jeff.Barczak@ice.dhs.org"],
    ["Courtney Norris", "Courtney.Norris@ice.dhs.org"],
    ["Noel Lee", "Noel.Lee@ice.dhs.org"],
    ["Timothy Black", "Timothy.Black@ice.dhs.org"],
    ["Judith Almodovar", "Judith.Almodovar@ice.dhs.org"],
    ["Joseph Flippo", "Joseph.Flippo@ice.dhs.org"],
    ["Shelley Howes", "Shelley.Howes@ice.dhs.org"],
    ["William Kloiber", "William.Kloiber@ice.dhs.org"],
    ["James Burns", "James.Burns@ice.dhs.org"],
    ["Christopher Wallace", "Christopher.Wallace@ice.dhs.org"],
    ["Sean Mullin", "Sean.Mullin@ice.dhs.org"],
    ["Bruce Gauthier", "Bruce.Gauthier@ice.dhs.org"],
    ["Mike Fernandez", "Mike.Fernandez@ice.dhs.org"],
    ["Charles Hester", "Charles.Hester@ice.dhs.org"],
    ["Patrick Murray", "Patrick.Murray@ice.dhs.org"],
    ["Patrick Kearns", "Patrick.Kearns@ice.dhs.org"],
    ["Rick Diaz", "Rick.Diaz@ice.dhs.org"],
    ["Victor Soto", "Victor.Soto@ice.dhs.org"],
    ["Leslie Brooks", "Leslie.Brooks@ice.dhs.org"],
    ["Balvin Dunn", "Balvin.Dunn@ice.dhs.org"],
    ["Eric Bradshaw", "Eric.Bradshaw@ice.dhs.org"],
    ["Jarat Lee Santikul", "Jarat.Lee.Santikul@ice.dhs.org"],
    ["Nicole Yandow", "Nicole.Yandow@ice.dhs.org"],
    ["Luis Maldonado", "Luis.Maldonado@ice.dhs.org"],
    ["Rich Gallagher", "Rich.Gallagher@ice.dhs.org"],
    ["Sir Streeter", "Sir.Streeter@ice.dhs.org"],
    ["Lynn Ziegler", "Lynn.Ziegler@ice.dhs.org"],
    ["Natalie Hancock", "Natalie.Hancock@ice.dhs.org"],
    ["Nelson Mercado", "Nelson.Mercado@ice.dhs.org"],
    ["Don Ivey", "Don.Ivey@ice.dhs.org"],
    ["Ruben Canales", "Ruben.Canales@ice.dhs.org"],
    ["Matthew Burns Jr", "Matthew.Burns.Jr@ice.dhs.org"],
    ["Don Bromberg", "Don.Bromberg@ice.dhs.org"],
    ["Jake ICE Phelps", "Jake.ICE.Phelps@ice.dhs.org"],
    ["Scott Bocksel", "Scott.Bocksel@ice.dhs.org"],
    ["Kevin 2509 Cronin", "Kevin.2509.Cronin@ice.dhs.org"],
    ["William Griffen", "William.Griffen@ice.dhs.org"],
    ["R. Franklin", "R.Franklin@ice.dhs.org"],
    ["Melanie Thomas", "Melanie.Thomas@ice.dhs.org"],
    ["Chris Woluewich", "Chris.Woluewich@ice.dhs.org"],
    ["Stewart Harvey", "Stewart.Harvey@ice.dhs.org"],
    ["daniel ramirez", "daniel.ramirez@ice.dhs.org"],
    ["Rachel Johnson", "Rachel.Johnson@ice.dhs.org"],
    ["Gary Reece", "Gary.Reece@ice.dhs.org"],
    ["Shelton Mirc", "Shelton.Mirc@ice.dhs.org"],
    ["Willy Ochoa", "Willy.Ochoa@ice.dhs.org"],
    ["Robert Babcock", "Robert.Babcock@ice.dhs.org"],
    ["Joe Del", "Joe.Del@ice.dhs.org"],
    ["Mark Zito", "Mark.Zito@ice.dhs.org"],
    ["Dustin Mehsling", "Dustin.Mehsling@ice.dhs.org"],
    ["Mike Macqueen", "Mike.Macqueen@ice.dhs.org"],
    ["Brad M.", "Brad.M@ice.dhs.org"],
    ["James Adams", "James.Adams@ice.dhs.org"],
    ["Gunnar Pedersen", "Gunnar.Pedersen@ice.dhs.org"],
    ["Andrew Onello", "Andrew.Onello@ice.dhs.org"],
    ["Jake Dobberke", "Jake.Dobberke@ice.dhs.org"],
    ["Michael McCarthy", "Michael.McCarthy@ice.dhs.org"],
    ["Daniel F Mikolay", "Daniel.F.Mikolay@ice.dhs.org"],
    ["R. Scott Harris", "R.Scott.Harris@ice.dhs.org"],
    ["Jason Samuels", "Jason.Samuels@ice.dhs.org"],
    ["Jada Keltz", "Jada.Keltz@ice.dhs.org"],
    ["Eric M.", "Eric.M@ice.dhs.org"],
    ["William Puff", "William.Puff@ice.dhs.org"],
    ["Patrick Fahey", "Patrick.Fahey@ice.dhs.org"],
    ["Chris Watkins", "Chris.Watkins@ice.dhs.org"],
    ["Monica Mapel", "Monica.Mapel@ice.dhs.org"],
    ["Scott Johnston", "Scott.Johnston@ice.dhs.org"],
    ["Jon N.", "Jon.N@ice.dhs.org"],
    ["Gabriel Martinez", "Gabriel.Martinez@ice.dhs.org"],
    ["LaShawn Powell", "LaShawn.Powell@ice.dhs.org"],
    ["Alex Chan", "Alex.Chan@ice.dhs.org"],
    ["Michael Calvo", "Michael.Calvo@ice.dhs.org"],
    ["Wendy Ireland", "Wendy.Ireland@ice.dhs.org"],
    ["Christopher Harms", "Christopher.Harms@ice.dhs.org"],
    ["Brian Stewart", "Brian.Stewart@ice.dhs.org"],
    ["David Morris", "David.Morris@ice.dhs.org"],
    ["John Deaton", "John.Deaton@ice.dhs.org"],
    ["Martin Spille", "Martin.Spille@ice.dhs.org"],
    ["Christopher Read", "Christopher.Read@ice.dhs.org"],
    ["Manuel De Leon", "Manuel.De.Leon@ice.dhs.org"],
    ["Brittany Tobias", "Brittany.Tobias@ice.dhs.org"],
    ["Van Stephens", "Van.Stephens@ice.dhs.org"],
    ["Brent Moore", "Brent.Moore@ice.dhs.org"],
    ["Samuel Nugent", "Samuel.Nugent@ice.dhs.org"],
    ["Scott Thompson", "Scott.Thompson@ice.dhs.org"],
    ["Brad Maison", "Brad.Maison@ice.dhs.org"],
    ["Matthew Lopez", "Matthew.Lopez@ice.dhs.org"],
    ["Christopher H.", "Christopher.H@ice.dhs.org"],
    ["Christopher Jeffreys", "Christopher.Jeffreys@ice.dhs.org"],
    ["Shane Watts", "Shane.Watts@ice.dhs.org"],
    ["Russ Spruance", "Russ.Spruance@ice.dhs.org"],
    ["Austin Shaver", "Austin.Shaver@ice.dhs.org"],
    ["Francis Kemp", "Francis.Kemp@ice.dhs.org"],
    ["Maria Gilbert", "Maria.Gilbert@ice.dhs.org"],
    ["Robert Alaniz Jr.", "Robert.Alaniz.Jr@ice.dhs.org"],
    ["Christopher Palazzo", "Christopher.Palazzo@ice.dhs.org"],
    ["Rebecca Fisher", "Rebecca.Fisher@ice.dhs.org"],
    ["Ronald Bissonnette", "Ronald.Bissonnette@ice.dhs.org"],
    ["Christopher Maloney", "Christopher.Maloney@ice.dhs.org"],
    ["Mark Rhoades", "Mark.Rhoades@ice.dhs.org"],
    ["Matthew Lester", "Matthew.Lester@ice.dhs.org"],
    ["John Schwink", "John.Schwink@ice.dhs.org"],
    ["Miguel Palomino", "Miguel.Palomino@ice.dhs.org"],
    ["michael morris", "michael.morris@ice.dhs.org"],
    ["Bryan Wheeler", "Bryan.Wheeler@ice.dhs.org"],
    ["richard wilkens", "richard.wilkens@ice.dhs.org"],
    ["Joshua F.", "Joshua.F@ice.dhs.org"],
    ["Joshua Kincaid", "Joshua.Kincaid@ice.dhs.org"],
    ["Christopher Carter", "Christopher.Carter@ice.dhs.org"],
    ["John Hardisson", "John.Hardisson@ice.dhs.org"],
    ["Sean Nails", "Sean.Nails@ice.dhs.org"],
    ["Derek Hadrian", "Derek.Hadrian@ice.dhs.org"],
    ["Neil Marley", "Neil.Marley@ice.dhs.org"],
    ["Gilbert Longoria", "Gilbert.Longoria@ice.dhs.org"],
    ["Gregory Styles", "Gregory.Styles@ice.dhs.org"],
    ["Rosevelt Holdin", "Rosevelt.Holdin@ice.dhs.org"],
    ["Jill Martin", "Jill.Martin@ice.dhs.org"],
    ["Scott Livingston", "Scott.Livingston@ice.dhs.org"],
    ["Gary C", "Gary.C@ice.dhs.org"],
    ["Richard Espinoza", "Richard.Espinoza@ice.dhs.org"],
    ["Cambisi Anthony", "Cambisi.Anthony@ice.dhs.org"],
    ["Alex Bragg", "Alex.Bragg@ice.dhs.org"],
    ["Ron Batley", "Ron.Batley@ice.dhs.org"],
    ["Aron Brown", "Aron.Brown@ice.dhs.org"],
    ["Dale Kramer", "Dale.Kramer@ice.dhs.org"],
    ["Howard KromeDMARC", "Howard.KromeDMARC@ice.dhs.org"],
    ["Antonino Giovenco", "Antonino.Giovenco@ice.dhs.org"],
    ["Ronald Lee", "Ronald.Lee@ice.dhs.org"],
    ["Jerrico Leason", "Jerrico.Leason@ice.dhs.org"],
    ["Vladimir Martinez-Jimenez", "Vladimir.Martinez-Jimenez@ice.dhs.org"],
    ["charlie250 Clem-Chalie", "charlie250.Clem-Chalie@ice.dhs.org"],
    ["Jerry Conrad", "Jerry.Conrad@ice.dhs.org"],
    ["Bryan Moser", "Bryan.Moser@ice.dhs.org"],
    ["David Vargas", "David.Vargas@ice.dhs.org"],
    ["Douglas Ruszcyk", "Douglas.Ruszcyk@ice.dhs.org"],
    ["Michael Higginbotham", "Michael.Higginbotham@ice.dhs.org"],
    ["Richard Kellner", "Richard.Kellner@ice.dhs.org"],
    ["Ken Yeung", "Ken.Yeung@ice.dhs.org"],
    ["Martinez Alberto", "Martinez.Alberto@ice.dhs.org"],
    ["Jessie Hernandez", "Jessie.Hernandez@ice.dhs.org"],
    ["Bill Tupy", "Bill.Tupy@ice.dhs.org"],
    ["Charles Hedges", "Charles.Hedges@ice.dhs.org"],
    ["Ryder Burpo", "Ryder.Burpo@ice.dhs.org"],
    ["Calivn Bradford", "Calivn.Bradford@ice.dhs.org"],
    ["Adam Parks", "Adam.Parks@ice.dhs.org"],
    ["James Bentz", "James.Bentz@ice.dhs.org"],
    ["Jason Madrigal", "Jason.Madrigal@ice.dhs.org"],
    ["Annemarie Brennan-Linnan", "Annemarie.Brennan-Linnan@ice.dhs.org"],
    ["Andrea Navarro", "Andrea.Navarro@ice.dhs.org"],
    ["Bernardo Pillot", "Bernardo.Pillot@ice.dhs.org"],
    ["Kyle Burns", "Kyle.Burns@ice.dhs.org"],
    ["Bryan McPherson", "Bryan.McPherson@ice.dhs.org"],
    ["Patrick M. Hudgens", "Patrick.M.Hudgens@ice.dhs.org"],
    ["Chaz Davis", "Chaz.Davis@ice.dhs.org"],
    ["John Ma", "John.Ma@ice.dhs.org"],
    ["Paul Waldron, CAMS", "Paul.Waldron@ice.dhs.org"],
    ["Kurtis Palm", "Kurtis.Palm@ice.dhs.org"],
    ["Jacob Ratliff", "Jacob.Ratliff@ice.dhs.org"],
    ["Willie Phillips", "Willie.Phillips@ice.dhs.org"],
    ["Sheila Blandon", "Sheila.Blandon@ice.dhs.org"],
    ["Peter Fellenz", "Peter.Fellenz@ice.dhs.org"],
    ["Eric Fletcher", "Eric.Fletcher@ice.dhs.org"],
    ["JD Y.", "JD.Y@ice.dhs.org"],
    ["Justin de Castro", "Justin.de.Castro@ice.dhs.org"],
    ["Julio Castro", "Julio.Castro@ice.dhs.org"],
    ["Jeffery Chappell, CFCE, ACE, EnCe", "Jeffery.Chappell@ice.dhs.org"],
    ["Justin Brown", "Justin.Brown@ice.dhs.org"],
    ["Kyle Hobart", "Kyle.Hobart@ice.dhs.org"],
    ["Brian Balkovec", "Brian.Balkovec@ice.dhs.org"],
    ["Beth Thomas", "Beth.Thomas@ice.dhs.org"],
    ["Miranda Collins", "Miranda.Collins@ice.dhs.org"],
    ["Anthony Estrella", "Anthony.Estrella@ice.dhs.org"],
    ["Christine Choo", "Christine.Choo@ice.dhs.org"],
    ["Jarrett Atkinson", "Jarrett.Atkinson@ice.dhs.org"],
    ["Joe Quattrocchi", "Joe.Quattrocchi@ice.dhs.org"],
    ["Anthony Miranda", "Anthony.Miranda@ice.dhs.org"],
    ["Richard Lall", "Richard.Lall@ice.dhs.org"],
    ["Chatham McCutcheon", "Chatham.McCutcheon@ice.dhs.org"],
    ["Josh Turner", "Josh.Turner@ice.dhs.org"],
    ["Jeffrey Martinez", "Jeffrey.Martinez@ice.dhs.org"],
    ["William Clark", "William.Clark@ice.dhs.org"],
    ["William Rusche", "William.Rusche@ice.dhs.org"],
    ["Christopher Cox", "Christopher.Cox@ice.dhs.org"],
    ["Olajuwon Davis", "Olajuwon.Davis@ice.dhs.org"],
    ["Bjorn Olson", "Bjorn.Olson@ice.dhs.org"],
    ["Sean Velazquez", "Sean.Velazquez@ice.dhs.org"],
    ["John Tucciarone", "John.Tucciarone@ice.dhs.org"],
    ["Jason Richardson", "Jason.Richardson@ice.dhs.org"],
    ["Derrick Chism", "Derrick.Chism@ice.dhs.org"],
    ["Leonid Peets", "Leonid.Peets@ice.dhs.org"],
    ["Timothy Tubbs", "Timothy.Tubbs@ice.dhs.org"],
    ["Elvia Wilcox", "Elvia.Wilcox@ice.dhs.org"],
    ["Daniel Main", "Daniel.Main@ice.dhs.org"],
    ["Miley James", "Miley.James@ice.dhs.org"],
    ["John Bustamante", "John.Bustamante@ice.dhs.org"],
    ["Mercedes Jordan", "Mercedes.Jordan@ice.dhs.org"],
    ["Jaime Maldonado", "Jaime.Maldonado@ice.dhs.org"],
    ["Kevin M Thompson", "Kevin.M.Thompson@ice.dhs.org"],
    ["Efren Chapa", "Efren.Chapa@ice.dhs.org"],
    ["Lee Totah", "Lee.Totah@ice.dhs.org"],
    ["Felix Ramos, Jr.", "Felix.Ramos@ice.dhs.org"],
    ["Robert Moore", "Robert.Moore@ice.dhs.org"],
    ["Willie Outlaw", "Willie.Outlaw@ice.dhs.org"],
    ["Tom Solem", "Tom.Solem@ice.dhs.org"],
    ["Michael Breder", "Michael.Breder@ice.dhs.org"],
    ["Dada C.", "Dada.C@ice.dhs.org"],
    ["Katlyn Woods", "Katlyn.Woods@ice.dhs.org"],
    ["Aaron Raynor", "Aaron.Raynor@ice.dhs.org"],
    ["chris lugard", "chris.lugard@ice.dhs.org"],
    ["Derrick Eleazer", "Derrick.Eleazer@ice.dhs.org"],
    ["Christopher Wyatt", "Christopher.Wyatt@ice.dhs.org"],
    ["Martin Gutierrez", "Martin.Gutierrez@ice.dhs.org"],
    ["Jean-Claude Nolan", "Jean-Claude.Nolan@ice.dhs.org"],
    ["Rick Null", "Rick.Null@ice.dhs.org"],
    ["Scott White", "Scott.White@ice.dhs.org"],
    ["Scott Saving", "Scott.Saving@ice.dhs.org"],
    ["Keith Chan", "Keith.Chan@ice.dhs.org"],
    ["Anthony Martinez", "Anthony.Martinez@ice.dhs.org"],
    ["Martin Bermudez", "Martin.Bermudez@ice.dhs.org"],
    ["David Williard", "David.Williard@ice.dhs.org"],
    ["Sean Hayhurst", "Sean.Hayhurst@ice.dhs.org"],
    ["Greg Hartfield", "Greg.Hartfield@ice.dhs.org"],
    ["Whitney Payte", "Whitney.Payte@ice.dhs.org"],
    ["Michael Gerwin", "Michael.Gerwin@ice.dhs.org"],
    ["Us Alerts", "Us.Alerts@ice.dhs.org"],
    ["Jim Reed", "Jim.Reed@ice.dhs.org"],
    ["Ryan Hubbard", "Ryan.Hubbard@ice.dhs.org"],
    ["Rosalie Bullen", "Rosalie.Bullen@ice.dhs.org"],
    ["Roberta Halls", "Roberta.Halls@ice.dhs.org"],
    ["George Cole", "George.Cole@ice.dhs.org"],
    ["A N", "A.N@ice.dhs.org"],
    ["Scott White", "Scott.White@ice.dhs.org"],
    ["Tim Jones", "Tim.Jones@ice.dhs.org"],
    ["Brent Oxley", "Brent.Oxley@ice.dhs.org"],
    ["Sergio De Leon Jr.", "Sergio.De.Leon.Jr@ice.dhs.org"],
    ["Jorge Oliva", "Jorge.Oliva@ice.dhs.org"],
    ["Larry Cannan", "Larry.Cannan@ice.dhs.org"],
    ["Ibrahim Ashmed", "Ibrahim.Ashmed@ice.dhs.org"],
    ["Todd L.", "Todd.L@ice.dhs.org"],
    ["ALEXANDER BRAGG", "ALEXANDER.BRAGG@ice.dhs.org"],
    ["Bill Sloan", "Bill.Sloan@ice.dhs.org"],
    ["Juan Ramirez", "Juan.Ramirez@ice.dhs.org"],
    ["Jasper Chan", "Jasper.Chan@ice.dhs.org"],
    ["Jared Smith", "Jared.Smith@ice.dhs.org"],
    ["Dr. John Drakeford", "Dr.John.Drakeford@ice.dhs.org"],
    ["Niko Ceja", "Niko.Ceja@ice.dhs.org"],
    ["Hector X Colon", "Hector.X.Colon@ice.dhs.org"],
    ["Rodney Abercrombie", "Rodney.Abercrombie@ice.dhs.org"],
    ["Joseph Williams", "Joseph.Williams@ice.dhs.org"],
    ["Matthew Gabe", "Matthew.Gabe@ice.dhs.org"],
    ["Kendra Jenkins", "Kendra.Jenkins@ice.dhs.org"],
    ["Eliu Estrada", "Eliu.Estrada@ice.dhs.org"],
    ["Brian Sherota", "Brian.Sherota@ice.dhs.org"],
    ["Sherilyn Streicker", "Sherilyn.Streicker@ice.dhs.org"],
    ["Amy Sprague", "Amy.Sprague@ice.dhs.org"],
    ["Joseph Foster", "Joseph.Foster@ice.dhs.org"],
    ["Roger L. Aarons", "Roger.L.Aarons@ice.dhs.org"],
    ["Brian Ramsey", "Brian.Ramsey@ice.dhs.org"],
    ["John Z.", "John.Z@ice.dhs.org"],
    ["Gene J Paulauskas", "Gene.J.Paulauskas@ice.dhs.org"],
    ["Michael Byrd", "Michael.Byrd@ice.dhs.org"],
    ["Glenn Spindel", "Glenn.Spindel@ice.dhs.org"],
    ["Miguel Ramirez", "Miguel.Ramirez@ice.dhs.org"],
    ["Brian Padian", "Brian.Padian@ice.dhs.org"],
    ["Mervyn J. De La Torre", "Mervyn.J.De.La.Torre@ice.dhs.org"],
    ["Chris Guyer", "Chris.Guyer@ice.dhs.org"],
    ["Matthew Christianson", "Matthew.Christianson@ice.dhs.org"],
    ["Mike Carney", "Mike.Carney@ice.dhs.org"],
    ["James Wilson, Jr", "James.Wilson@ice.dhs.org"],
    ["David Byrd", "David.Byrd@ice.dhs.org"],
    ["Harold Honegger", "Harold.Honegger@ice.dhs.org"],
    ["Shenan Carroll", "Shenan.Carroll@ice.dhs.org"],
    ["Richard Lyons", "Richard.Lyons@ice.dhs.org"],
    ["Bruce Busby", "Bruce.Busby@ice.dhs.org"],
    ["Kelvin Glymph", "Kelvin.Glymph@ice.dhs.org"],
    ["Robert Holscher", "Robert.Holscher@ice.dhs.org"],
    ["Nicole Solander", "Nicole.Solander@ice.dhs.org"],
    ["Cynthia Ludington", "Cynthia.Ludington@ice.dhs.org"],
    ["Tim Westlove", "Tim.Westlove@ice.dhs.org"],
    ["Rajeev Sharma", "Rajeev.Sharma@ice.dhs.org"],
    ["Rich Nicorvo, CEM, PMP", "Rich.Nicorvo@ice.dhs.org"],
    ["Miguel L Carrasquillo", "Miguel.L.Carrasquillo@ice.dhs.org"],
    ["Michael McLaughlin", "Michael.McLaughlin@ice.dhs.org"],
    ["Charles Gibbs", "Charles.Gibbs@ice.dhs.org"],
    ["Logan W.", "Logan.W@ice.dhs.org"],
    ["Christopher Kudless", "Christopher.Kudless@ice.dhs.org"],
    ["Jeannetta S Evans", "Jeannetta.S.Evans@ice.dhs.org"],
    ["Kelly Anderson CHS IV, SSI", "Kelly.Anderson.CHS.IV@ice.dhs.org"],
    ["Jesse Lewis", "Jesse.Lewis@ice.dhs.org"],
    ["Chuck Kirk", "Chuck.Kirk@ice.dhs.org"],
    ["Joanne Johnson", "Joanne.Johnson@ice.dhs.org"],
    ["Paul Valvo", "Paul.Valvo@ice.dhs.org"],
    ["Paul Bevard", "Paul.Bevard@ice.dhs.org"],
    ["James Adams", "James.Adams@ice.dhs.org"],
    ["Heather A.", "Heather.A@ice.dhs.org"],
    ["Jason Edmister", "Jason.Edmister@ice.dhs.org"],
    ["Christopher Jacobs", "Christopher.Jacobs@ice.dhs.org"],
    ["June Adams", "June.Adams@ice.dhs.org"],
    ["Frank P.", "Frank.P@ice.dhs.org"],
    ["Kristal Pena", "Kristal.Pena@ice.dhs.org"],
    ["Bhrugesh Patel", "Bhrugesh.Patel@ice.dhs.org"],
    ["Tim Lenzen", "Tim.Lenzen@ice.dhs.org"],
    ["Christian Lamborn", "Christian.Lamborn@ice.dhs.org"],
    ["Gerardo C.", "Gerardo.C@ice.dhs.org"],
    ["Marco Ruiz", "Marco.Ruiz@ice.dhs.org"],
    ["Gabriel Ruiz", "Gabriel.Ruiz@ice.dhs.org"],
    ["Creigon Ellis", "Creigon.Ellis@ice.dhs.org"],
    ["Daniel Finn", "Daniel.Finn@ice.dhs.org"],
    ["Lagarion Brown", "Lagarion.Brown@ice.dhs.org"],
    ["Ariel Valdez", "Ariel.Valdez@ice.dhs.org"],
    ["Eli Moran", "Eli.Moran@ice.dhs.org"],
    ["Lucas Penn", "Lucas.Penn@ice.dhs.org"],
    ["Adam Khalil", "Adam.Khalil@ice.dhs.org"],
    ["Linda Past", "Linda.Past@ice.dhs.org"],
    ["Faith S.", "Faith.S@ice.dhs.org"],
    ["Ron Seely", "Ron.Seely@ice.dhs.org"],
    ["Andrew Chiles", "Andrew.Chiles@ice.dhs.org"],
    ["Ricky Colegrove", "Ricky.Colegrove@ice.dhs.org"],
    ["Dan Athanasaw", "Dan.Athanasaw@ice.dhs.org"],
    ["James Banks", "James.Banks@ice.dhs.org"],
    ["Carol Lazzaro", "Carol.Lazzaro@ice.dhs.org"],
    ["Greenbaum Alan", "Greenbaum.Alan@ice.dhs.org"],
    ["Sylvester Phekoo", "Sylvester.Phekoo@ice.dhs.org"],
    ["Chris Chamberlain", "Chris.Chamberlain@ice.dhs.org"],
    ["Sara Badger", "Sara.Badger@ice.dhs.org"],
    ["Brenda Allport", "Brenda.Allport@ice.dhs.org"],
    ["Jake Summers", "Jake.Summers@ice.dhs.org"],
    ["Chris Oslin", "Chris.Oslin@ice.dhs.org"],
    ["Daniel Kaiser, SFPC", "Daniel.Kaiser@ice.dhs.org"],
    ["CHRISTOPHER GAMEZ", "CHRISTOPHER.GAMEZ@ice.dhs.org"],
    ["Mark Elias", "Mark.Elias@ice.dhs.org"],
    ["Anthony Webb", "Anthony.Webb@ice.dhs.org"],
    ["William Flood", "William.Flood@ice.dhs.org"],
    ["Regina Calhoun", "Regina.Calhoun@ice.dhs.org"],
    ["David Singh", "David.Singh@ice.dhs.org"],
    ["Tanika Sanders", "Tanika.Sanders@ice.dhs.org"],
    ["Mary De Anda-Ybarra", "Mary.De.Anda-Ybarra@ice.dhs.org"],
    ["James Gwinn", "James.Gwinn@ice.dhs.org"],
    ["Walter Le Roy", "Walter.Le.Roy@ice.dhs.org"],
    ["Howard Bolick", "Howard.Bolick@ice.dhs.org"],
    ["Rik Webb", "Rik.Webb@ice.dhs.org"],
    ["John A", "John.A@ice.dhs.org"],
    ["Michael Sharp", "Michael.Sharp@ice.dhs.org"],
    ["Nathan Rasper", "Nathan.Rasper@ice.dhs.org"],
    ["Gina Mostafaie", "Gina.Mostafaie@ice.dhs.org"],
    ["Tammy Spicer", "Tammy.Spicer@ice.dhs.org"],
    ["Dan Cutchens", "Dan.Cutchens@ice.dhs.org"],
    ["Doug Green", "Doug.Green@ice.dhs.org"],
    ["Douglas Gilmer", "Douglas.Gilmer@ice.dhs.org"],
    ["Dee Norton", "Dee.Norton@ice.dhs.org"],
    ["Jason Henry", "Jason.Henry@ice.dhs.org"],
    ["Rafa Conde", "Rafa.Conde@ice.dhs.org"],
    ["Jere Miles", "Jere.Miles@ice.dhs.org"],
    ["Stephen Miller", "Stephen.Miller@ice.dhs.org"],
    ["Fidel Esparza III", "Fidel.Esparza.III@ice.dhs.org"],
    ["Benjamin Buchta", "Benjamin.Buchta@ice.dhs.org"],
    ["Wm. David Jones", "Wm.David.Jones@ice.dhs.org"],
    ["Tim Colson", "Tim.Colson@ice.dhs.org"],
    ["Toni Dupard-North", "Toni.Dupard-North@ice.dhs.org"],
    ["Elhrick C.", "Elhrick.C@ice.dhs.org"],
    ["Joshua Rodriguez", "Joshua.Rodriguez@ice.dhs.org"],
    ["Robert Bernal", "Robert.Bernal@ice.dhs.org"],
    ["Elizabeth Leong", "Elizabeth.Leong@ice.dhs.org"],
    ["Casie Matter", "Casie.Matter@ice.dhs.org"],
    ["Edgardo Centeno", "Edgardo.Centeno@ice.dhs.org"],
    ["David Nejand", "David.Nejand@ice.dhs.org"],
    ["JUSTIN DILONE", "JUSTIN.DILONE@ice.dhs.org"],
    ["Niko DeCristofaro", "Niko.DeCristofaro@ice.dhs.org"],
    ["Noor Phillips", "Noor.Phillips@ice.dhs.org"],
    ["Frank Franco", "Frank.Franco@ice.dhs.org"],
    ["William Chin", "William.Chin@ice.dhs.org"],
    ["Douglas McKenna, PMP", "Douglas.McKenna@ice.dhs.org"],
    ["Cherie Go", "Cherie.Go@ice.dhs.org"],
    ["Kenneth Padilla", "Kenneth.Padilla@ice.dhs.org"],
    ["Luis Rendon", "Luis.Rendon@ice.dhs.org"],
    ["George Sterling", "George.Sterling@ice.dhs.org"],
    ["Jack Bennett", "Jack.Bennett@ice.dhs.org"],
    ["Marc Moore", "Marc.Moore@ice.dhs.org"],
    ["Jeffrey D. Lynch", "Jeffrey.D.Lynch@ice.dhs.org"],
    ["Hilary Pullen", "Hilary.Pullen@ice.dhs.org"],
    ["Timothy Aitken", "Timothy.Aitken@ice.dhs.org"],
    ["C. Denise Moore", "C.Denise.Moore@ice.dhs.org"],
    ["Al Santos", "Al.Santos@ice.dhs.org"],
    ["Scott Rozzelle", "Scott.Rozzelle@ice.dhs.org"],
    ["Sean Ervin", "Sean.Ervin@ice.dhs.org"],
    ["Kristy Singletary", "Kristy.Singletary@ice.dhs.org"],
    ["Will Williams", "Will.Williams@ice.dhs.org"],
    ["Conrad Agagan", "Conrad.Agagan@ice.dhs.org"],
    ["Kelly Horecky", "Kelly.Horecky@ice.dhs.org"],
    ["Joseph Lombardo", "Joseph.Lombardo@ice.dhs.org"],
    ["John Martinez", "John.Martinez@ice.dhs.org"],
    ["Tarah Murphy", "Tarah.Murphy@ice.dhs.org"],
    ["Jacqueline Haile", "Jacqueline.Haile@ice.dhs.org"],
    ["Richard Catalon MS, PMP, CISA", "Richard.Catalon.MS@ice.dhs.org"],
    ["Jennell Thomas Lewis", "Jennell.Thomas.Lewis@ice.dhs.org"],
    ["Dionne Jones", "Dionne.Jones@ice.dhs.org"],
    ["Robert Rochester", "Robert.Rochester@ice.dhs.org"],
    ["Jay Dell", "Jay.Dell@ice.dhs.org"],
    ["Robert J. Alfieri", "Robert.J.Alfieri@ice.dhs.org"],
    ["Reiss K.", "Reiss.K@ice.dhs.org"],
    ["Scott Blake", "Scott.Blake@ice.dhs.org"],
    ["Candace Kerr", "Candace.Kerr@ice.dhs.org"],
    ["Shonchotsani Y.", "Shonchotsani.Y@ice.dhs.org"],
    ["Lyle Boelens", "Lyle.Boelens@ice.dhs.org"],
    ["William Waddington", "William.Waddington@ice.dhs.org"],
    ["Susanna Warner", "Susanna.Warner@ice.dhs.org"],
    ["Luisito Maligat", "Luisito.Maligat@ice.dhs.org"],
    ["Daniel Gross", "Daniel.Gross@ice.dhs.org"],
    ["Lovely Epps", "Lovely.Epps@ice.dhs.org"],
    ["Pamela Ashanti-Griggs", "Pamela.Ashanti-Griggs@ice.dhs.org"],
    ["Douglas Rustan", "Douglas.Rustan@ice.dhs.org"],
    ["Kristine Brisson", "Kristine.Brisson@ice.dhs.org"],
    ["Beau Allen", "Beau.Allen@ice.dhs.org"],
    ["Miguel Vergara", "Miguel.Vergara@ice.dhs.org"],
    ["Linda Tadrus", "Linda.Tadrus@ice.dhs.org"],
    ["Kristal Watts", "Kristal.Watts@ice.dhs.org"],
    ["Corey Snyder", "Corey.Snyder@ice.dhs.org"],
    ["Derek Long", "Derek.Long@ice.dhs.org"],
    ["Amy Powell", "Amy.Powell@ice.dhs.org"],
    ["Katherine Sheridan", "Katherine.Sheridan@ice.dhs.org"],
    ["Megan Littlejohn", "Megan.Littlejohn@ice.dhs.org"],
    ["Tonja Cosey", "Tonja.Cosey@ice.dhs.org"],
    ["Robert Hobart", "Robert.Hobart@ice.dhs.org"],
    ["Jesse Williams", "Jesse.Williams@ice.dhs.org"],
    ["Anita Holland", "Anita.Holland@ice.dhs.org"],
    ["Mike Burtis", "Mike.Burtis@ice.dhs.org"],
    ["Daniel Mackey", "Daniel.Mackey@ice.dhs.org"],
    ["Jill Hicks", "Jill.Hicks@ice.dhs.org"],
    ["Felicia Clark", "Felicia.Clark@ice.dhs.org"],
    ["Marcella Hayes", "Marcella.Hayes@ice.dhs.org"],
    ["Dennis Garner", "Dennis.Garner@ice.dhs.org"],
    ["Amar Mundzahasic", "Amar.Mundzahasic@ice.dhs.org"],
    ["Miguel Cruz", "Miguel.Cruz@ice.dhs.org"],
    ["Nathalie Asher", "Nathalie.Asher@ice.dhs.org"],
    ["Lisa Lockman", "Lisa.Lockman@ice.dhs.org"],
    ["C. Denise Winter", "C.Denise.Winter@ice.dhs.org"],
    ["Denise Moore", "Denise.Moore@ice.dhs.org"],
    ["Robert Alfieri", "Robert.Alfieri@ice.dhs.org"],
    ["Cuthbert Jacobs", "Cuthbert.Jacobs@ice.dhs.org"],
    ["Garry L Branch", "Garry.L.Branch@ice.dhs.org"],
    ["Ray Linsdey", "Ray.Linsdey@ice.dhs.org"],
    ["Benny Smith", "Benny.Smith@ice.dhs.org"],
    ["Alfredo Campos", "Alfredo.Campos@ice.dhs.org"],
    ["Chelsea Elston", "Chelsea.Elston@ice.dhs.org"],
    ["Damian Matthews", "Damian.Matthews@ice.dhs.org"],
    ["Jeff Searls", "Jeff.Searls@ice.dhs.org"],
    ["Paul Hester", "Paul.Hester@ice.dhs.org"],
    ["Chrissy Ward", "Chrissy.Ward@ice.dhs.org"],
    ["Renee Shawn Clement", "Renee.Shawn.Clement@ice.dhs.org"],
    ["charles willis", "charles.willis@ice.dhs.org"],
    ["Mike Skelton", "Mike.Skelton@ice.dhs.org"],
    ["Cynthia Ahmed", "Cynthia.Ahmed@ice.dhs.org"],
    ["Linda Ward", "Linda.Ward@ice.dhs.org"],
    ["elham kharazmi", "elham.kharazmi@ice.dhs.org"],
    ["Cheryl Poisson", "Cheryl.Poisson@ice.dhs.org"],
    ["Robert brother Culley", "Robert.brother.Culley@ice.dhs.org"],
    ["Patrick Contreras", "Patrick.Contreras@ice.dhs.org"],
    ["Linwood Weaver", "Linwood.Weaver@ice.dhs.org"],
    ["Kathy Baker", "Kathy.Baker@ice.dhs.org"],
    ["Robin Gladden", "Robin.Gladden@ice.dhs.org"],
    ["Rene Rodriguez", "Rene.Rodriguez@ice.dhs.org"],
    ["Margaret Garcia", "Margaret.Garcia@ice.dhs.org"],
    ["Pam Briggs", "Pam.Briggs@ice.dhs.org"],
    ["Megan Hier", "Megan.Hier@ice.dhs.org"],
    ["Rita Thompson", "Rita.Thompson@ice.dhs.org"],
    ["Thomas P. Giles", "Thomas.P.Giles@ice.dhs.org"],
    ["Cyrena Khoury", "Cyrena.Khoury@ice.dhs.org"],
    ["John Milian", "John.Milian@ice.dhs.org"],
    ["Dan Ragsdale", "Dan.Ragsdale@ice.dhs.org"],
    ["David Jennings", "David.Jennings@ice.dhs.org"],
    ["Walt Cain", "Walt.Cain@ice.dhs.org"],
    ["Michael W. Meade", "Michael.W.Meade@ice.dhs.org"],
    ["Henry Lucero", "Henry.Lucero@ice.dhs.org"],
    ["Janet Williams", "Janet.Williams@ice.dhs.org"],
    ["Dilip Kinra, PMP, ITILv3", "Dilip.Kinra@ice.dhs.org"],
    ["Trey Lund", "Trey.Lund@ice.dhs.org"],
    ["Stephen Roncone", "Stephen.Roncone@ice.dhs.org"],
    ["Marisa F.", "Marisa.F@ice.dhs.org"],
    ["Patrick Knowles, SHRM-CP", "Patrick.Knowles@ice.dhs.org"],
    ["Paul McCloskey", "Paul.McCloskey@ice.dhs.org"],
    ["Elizabeth Kennett", "Elizabeth.Kennett@ice.dhs.org"],
    ["Elizabeth Kiley", "Elizabeth.Kiley@ice.dhs.org"],
    ["Alethea Boss", "Alethea.Boss@ice.dhs.org"],
    ["Shawn Byers", "Shawn.Byers@ice.dhs.org"],
    ["Terry Johnston", "Terry.Johnston@ice.dhs.org"],
    ["Bryan Wilcox", "Bryan.Wilcox@ice.dhs.org"],
    ["Howard L. Weisman", "Howard.L.Weisman@ice.dhs.org"],
    ["Regina McCully", "Regina.McCully@ice.dhs.org"],
    ["Nadia S.", "Nadia.S@ice.dhs.org"],
    ["Paul A. McBride", "Paul.A.McBride@ice.dhs.org"],
    ["Michelle Brito", "Michelle.Brito@ice.dhs.org"],
    ["Jennifer Uriostegui", "Jennifer.Uriostegui@ice.dhs.org"],
    ["Michellette Green", "Michellette.Green@ice.dhs.org"],
    ["Duane Hemphill", "Duane.Hemphill@ice.dhs.org"],
    ["Christopher Crespo", "Christopher.Crespo@ice.dhs.org"],
    ["Floyd Sam Farmer", "Floyd.Sam.Farmer@ice.dhs.org"],
    ["Lisa Watson", "Lisa.Watson@ice.dhs.org"],
    ["John P.", "John.P@ice.dhs.org"],
    ["Briana Kreibich", "Briana.Kreibich@ice.dhs.org"],
    ["Kara Eutsler", "Kara.Eutsler@ice.dhs.org"],
    ["Aida Polite", "Aida.Polite@ice.dhs.org"],
    ["Erin Dowling", "Erin.Dowling@ice.dhs.org"],
    ["Jeffrey Morin", "Jeffrey.Morin@ice.dhs.org"],
    ["Douglas Nagel", "Douglas.Nagel@ice.dhs.org"],
    ["Martha Wamunyu", "Martha.Wamunyu@ice.dhs.org"],
    ["James Shaver", "James.Shaver@ice.dhs.org"],
    ["Daniel Jaramillo", "Daniel.Jaramillo@ice.dhs.org"],
    ["Joseph Nicolai", "Joseph.Nicolai@ice.dhs.org"],
    ["Evelin Montenegro", "Evelin.Montenegro@ice.dhs.org"],
    ["Mike White", "Mike.White@ice.dhs.org"],
    ["Wes McCarville", "Wes.McCarville@ice.dhs.org"],
    ["DAVID DRASIN", "DAVID.DRASIN@ice.dhs.org"],
    ["Isaiah S. Hughes", "Isaiah.S.Hughes@ice.dhs.org"],
    ["Rose Riley", "Rose.Riley@ice.dhs.org"],
    ["Kathryn Briskie", "Kathryn.Briskie@ice.dhs.org"],
    ["Roderick Robinson", "Roderick.Robinson@ice.dhs.org"],
    ["Samantha Seaman", "Samantha.Seaman@ice.dhs.org"],
    ["Billy Lee, REHS&#x2F;RS", "Billy.Lee@ice.dhs.org"],
    ["Marie Howell", "Marie.Howell@ice.dhs.org"],
    ["Michael Chesnut", "Michael.Chesnut@ice.dhs.org"],
    ["Chad Walton", "Chad.Walton@ice.dhs.org"],
    ["Cesar Sarinana", "Cesar.Sarinana@ice.dhs.org"],
    ["Mattie Johnson-Ross", "Mattie.Johnson-Ross@ice.dhs.org"],
    ["Cheri Kennedy", "Cheri.Kennedy@ice.dhs.org"],
    ["Tonya G. Nowlin", "Tonya.G.Nowlin@ice.dhs.org"],
    ["Matt Gowin", "Matt.Gowin@ice.dhs.org"],
    ["Moris Tobar", "Moris.Tobar@ice.dhs.org"],
    ["Floyd Gibson", "Floyd.Gibson@ice.dhs.org"],
    ["Darren Williams", "Darren.Williams@ice.dhs.org"],
    ["Antonio James, MBA", "Antonio.James@ice.dhs.org"],
    ["Holly Taylor", "Holly.Taylor@ice.dhs.org"],
    ["David Thomas", "David.Thomas@ice.dhs.org"],
    ["Rick Pulsinelli, CPA", "Rick.Pulsinelli@ice.dhs.org"],
    ["Alex Folami", "Alex.Folami@ice.dhs.org"],
    ["Dave Jones", "Dave.Jones@ice.dhs.org"],
    ["Ralph Ferguson, MS, MBA", "Ralph.Ferguson@ice.dhs.org"],
    ["David Adams, MBA, CSHS", "David.Adams@ice.dhs.org"],
    ["marion harris", "marion.harris@ice.dhs.org"],
    ["Jacquese DuBose", "Jacquese.DuBose@ice.dhs.org"],
    ["KEHINDE Lateef", "KEHINDE.Lateef@ice.dhs.org"],
    ["angela bozieux", "angela.bozieux@ice.dhs.org"],
    ["Rachael Zarlinski", "Rachael.Zarlinski@ice.dhs.org"],
    ["Emily Sprouse", "Emily.Sprouse@ice.dhs.org"],
    ["Taria Ramos", "Taria.Ramos@ice.dhs.org"],
    ["Maria Alexandra Laborde", "Maria.Alexandra.Laborde@ice.dhs.org"],
    ["Pallavi Shirole", "Pallavi.Shirole@ice.dhs.org"],
    ["Brandon Lowy", "Brandon.Lowy@ice.dhs.org"],
    ["Kelley Fowler", "Kelley.Fowler@ice.dhs.org"],
    ["Kasey Podzius", "Kasey.Podzius@ice.dhs.org"],
    ["Michael McFarland", "Michael.McFarland@ice.dhs.org"],
    ["Rodion Tadenev", "Rodion.Tadenev@ice.dhs.org"],
    ["Elizaveta Ivanova", "Elizaveta.Ivanova@ice.dhs.org"],
    ["Demetirus Cook", "Demetirus.Cook@ice.dhs.org"],
    ["Curtis George White", "Curtis.George.White@ice.dhs.org"],
    ["Enrique J. San Miguel-Ruiz", "Enrique.J.San.Miguel-Ruiz@ice.dhs.org"],
    ["Bao Q. Nguyen", "Bao.Q.Nguyen@ice.dhs.org"],
    ["Amanda Fischer", "Amanda.Fischer@ice.dhs.org"],
    ["Amanda J.", "Amanda.J@ice.dhs.org"],
    ["Luke Nelson", "Luke.Nelson@ice.dhs.org"],
    ["Steven Vezos", "Steven.Vezos@ice.dhs.org"],
    ["Matt Chan", "Matt.Chan@ice.dhs.org"],
    ["Dionne Gill", "Dionne.Gill@ice.dhs.org"],
    ["Alok Kale", "Alok.Kale@ice.dhs.org"],
    ["Deborah Ho", "Deborah.Ho@ice.dhs.org"],
    ["Carlo Zayas Morales", "Carlo.Zayas.Morales@ice.dhs.org"],
    ["Ross Militello", "Ross.Militello@ice.dhs.org"],
    ["Nicholle Hempel", "Nicholle.Hempel@ice.dhs.org"],
    ["Geoffrey Ling", "Geoffrey.Ling@ice.dhs.org"],
    ["Margo Strauss", "Margo.Strauss@ice.dhs.org"],
    ["Stephanie Williams", "Stephanie.Williams@ice.dhs.org"],
    ["Tatiana Boza", "Tatiana.Boza@ice.dhs.org"],
    ["Amanda Brown", "Amanda.Brown@ice.dhs.org"],
    ["Zachary Ista", "Zachary.Ista@ice.dhs.org"],
    ["Matt Hall", "Matt.Hall@ice.dhs.org"],
    ["Kate Cazayoux Brownlee", "Kate.Cazayoux.Brownlee@ice.dhs.org"],
    ["Anne Tokoph", "Anne.Tokoph@ice.dhs.org"],
    ["Shiraz Panthaky", "Shiraz.Panthaky@ice.dhs.org"],
    ["Gwendolyn F.", "Gwendolyn.F@ice.dhs.org"],
    ["Danielle Paas", "Danielle.Paas@ice.dhs.org"],
    ["David Etches", "David.Etches@ice.dhs.org"],
    ["Shani Dennis Williform", "Shani.Dennis.Williform@ice.dhs.org"],
    ["Erin Clifford", "Erin.Clifford@ice.dhs.org"],
    ["Karla Mari DeVera", "Karla.Mari.DeVera@ice.dhs.org"],
    ["Terry Louie", "Terry.Louie@ice.dhs.org"],
    ["Alyssa Benton", "Alyssa.Benton@ice.dhs.org"],
    ["Rob Ramey", "Rob.Ramey@ice.dhs.org"],
    ["Scot Rittenberg", "Scot.Rittenberg@ice.dhs.org"],
    ["Carrie Johnson", "Carrie.Johnson@ice.dhs.org"],
    ["Elizabeth Gross", "Elizabeth.Gross@ice.dhs.org"],
    ["Kevin Bindus", "Kevin.Bindus@ice.dhs.org"],
    ["Daniel Rah", "Daniel.Rah@ice.dhs.org"],
    ["Julie Heaner Plavsic", "Julie.Heaner.Plavsic@ice.dhs.org"],
    ["Walter Chahanovich", "Walter.Chahanovich@ice.dhs.org"],
    ["Blake Northway", "Blake.Northway@ice.dhs.org"],
    ["Michael Brennan", "Michael.Brennan@ice.dhs.org"],
    ["Lisa Schultz", "Lisa.Schultz@ice.dhs.org"],
    ["Patrick Dyson", "Patrick.Dyson@ice.dhs.org"],
    ["Ryan Seuradge", "Ryan.Seuradge@ice.dhs.org"],
    ["Michelle Phillips", "Michelle.Phillips@ice.dhs.org"],
    ["Robert Smith", "Robert.Smith@ice.dhs.org"],
    ["Paul Hunker", "Paul.Hunker@ice.dhs.org"],
    ["Chris Coxe", "Chris.Coxe@ice.dhs.org"],
    ["Cheryl Gutridge", "Cheryl.Gutridge@ice.dhs.org"],
    ["Lisa Batey", "Lisa.Batey@ice.dhs.org"],
    ["David Walther", "David.Walther@ice.dhs.org"],
    ["Barrett Mc", "Barrett.Mc@ice.dhs.org"],
    ["Jonathan Gibbs", "Jonathan.Gibbs@ice.dhs.org"],
    ["Michael Amezquita", "Michael.Amezquita@ice.dhs.org"],
    ["Krista Jones", "Krista.Jones@ice.dhs.org"],
    ["Bob Feagin", "Bob.Feagin@ice.dhs.org"],
    ["Marguerite Mills", "Marguerite.Mills@ice.dhs.org"],
    ["Kathleen Zapata", "Kathleen.Zapata@ice.dhs.org"],
    ["Lee Crystal", "Lee.Crystal@ice.dhs.org"],
    ["Lisa Putnam", "Lisa.Putnam@ice.dhs.org"],
    ["Richard Brown", "Richard.Brown@ice.dhs.org"],
    ["Randy Kung", "Randy.Kung@ice.dhs.org"],
    ["Maryellen Meymarian", "Maryellen.Meymarian@ice.dhs.org"],
    ["William Padish", "William.Padish@ice.dhs.org"],
    ["Charles Smith", "Charles.Smith@ice.dhs.org"],
    ["Melissa Maack", "Melissa.Maack@ice.dhs.org"],
    ["Rich OBrien", "Rich.OBrien@ice.dhs.org"],
    ["Thomas P Molloy", "Thomas.P.Molloy@ice.dhs.org"],
    ["Brian Jasperson", "Brian.Jasperson@ice.dhs.org"],
    ["Travis Graham", "Travis.Graham@ice.dhs.org"],
    ["LaToya Tribue", "LaToya.Tribue@ice.dhs.org"],
    ["Brian Turner", "Brian.Turner@ice.dhs.org"],
    ["Wilbert Spooner, Jr", "Wilbert.Spooner@ice.dhs.org"],
    ["Neal Patel", "Neal.Patel@ice.dhs.org"],
    ["Annie McElearney", "Annie.McElearney@ice.dhs.org"],
    ["Louis Russo", "Louis.Russo@ice.dhs.org"],
    ["Winnette Mcfail", "Winnette.Mcfail@ice.dhs.org"],
    ["Matthew Hall", "Matthew.Hall@ice.dhs.org"],
    ["Matthew Schautz", "Matthew.Schautz@ice.dhs.org"],
    ["Charles Neil Floyd", "Charles.Neil.Floyd@ice.dhs.org"],
    ["Michael-ru Null", "Michael-ru.Null@ice.dhs.org"],
    ["Lisa Schow Schow", "Lisa.Schow.Schow@ice.dhs.org"],
    ["Greg Ball", "Greg.Ball@ice.dhs.org"],
    ["Robert Pate", "Robert.Pate@ice.dhs.org"],
    ["Jenea Marjama, MBA", "Jenea.Marjama@ice.dhs.org"],
    ["McClintock E", "McClintock.E@ice.dhs.org"],
    ["Luciana Dubuc", "Luciana.Dubuc@ice.dhs.org"],
    ["Jonathan Graham", "Jonathan.Graham@ice.dhs.org"],
    ["Peter Mina", "Peter.Mina@ice.dhs.org"],
    ["Julio Ayala", "Julio.Ayala@ice.dhs.org"],
    ["Ryan Grant", "Ryan.Grant@ice.dhs.org"],
    ["Josh Levy", "Josh.Levy@ice.dhs.org"],
    ["Meghan Funk", "Meghan.Funk@ice.dhs.org"],
    ["Priscilla Gabela", "Priscilla.Gabela@ice.dhs.org"],
    ["Ann Atalla", "Ann.Atalla@ice.dhs.org"],
    ["Steve Chapman", "Steve.Chapman@ice.dhs.org"],
    ["Michael Dreher", "Michael.Dreher@ice.dhs.org"],
    ["Nicole Schroeder", "Nicole.Schroeder@ice.dhs.org"],
    ["Geoff R.", "Geoff.R@ice.dhs.org"],
    ["Jacob Painter", "Jacob.Painter@ice.dhs.org"],
    ["Ian Tomasic", "Ian.Tomasic@ice.dhs.org"],
    ["Jenelle Williams Oyekan", "Jenelle.Williams.Oyekan@ice.dhs.org"],
    ["Devin Garcia", "Devin.Garcia@ice.dhs.org"],
    ["Sandra Osmanovic, Esq.", "Sandra.Osmanovic@ice.dhs.org"],
    ["Angel Olivera", "Angel.Olivera@ice.dhs.org"],
    ["Lynette Lowe", "Lynette.Lowe@ice.dhs.org"],
    ["Ryan Stubbs", "Ryan.Stubbs@ice.dhs.org"],
    ["Alex Lee", "Alex.Lee@ice.dhs.org"],
    ["Tamaira Rivera", "Tamaira.Rivera@ice.dhs.org"],
    ["Christopher Alwood", "Christopher.Alwood@ice.dhs.org"],
    ["Vidhya Amirthalingam", "Vidhya.Amirthalingam@ice.dhs.org"],
    ["Katherine Aquavia Thomas", "Katherine.Aquavia.Thomas@ice.dhs.org"],
    ["Adam Panopoulos", "Adam.Panopoulos@ice.dhs.org"],
    ["Jason Stanley", "Jason.Stanley@ice.dhs.org"],
    ["Cathy N.", "Cathy.N@ice.dhs.org"],
    ["Gabe Kennon", "Gabe.Kennon@ice.dhs.org"],
    ["Suzanne L.", "Suzanne.L@ice.dhs.org"],
    ["Kimberly Burgess", "Kimberly.Burgess@ice.dhs.org"],
    ["Rey de la Garza", "Rey.de.la.Garza@ice.dhs.org"],
    ["Monica Mubaraki", "Monica.Mubaraki@ice.dhs.org"],
    ["Andrew Fonte", "Andrew.Fonte@ice.dhs.org"],
    ["Kelsey L.", "Kelsey.L@ice.dhs.org"],
    ["Christine Longo", "Christine.Longo@ice.dhs.org"],
    ["Andrew Bonic", "Andrew.Bonic@ice.dhs.org"],
    ["Francisco J. Muniz", "Francisco.J.Muniz@ice.dhs.org"],
    ["Michael J. Wynne", "Michael.J.Wynne@ice.dhs.org"],
    ["Pamela Eclar Diéguez", "Pamela.Eclar.Diéguez@ice.dhs.org"],
    ["Kristin D. Brudy", "Kristin.D.Brudy@ice.dhs.org"],
    ["Alexander Laytin", "Alexander.Laytin@ice.dhs.org"],
    ["Lacy Brinson McAndrew", "Lacy.Brinson.McAndrew@ice.dhs.org"],
    ["Alford Danzy", "Alford.Danzy@ice.dhs.org"],
    ["Sarah Ellison", "Sarah.Ellison@ice.dhs.org"],
    ["Susan F. Bayles", "Susan.F.Bayles@ice.dhs.org"],
    ["George Ward", "George.Ward@ice.dhs.org"],
    ["Jason Bailey", "Jason.Bailey@ice.dhs.org"],
    ["Frank Miqueo, MPA", "Frank.Miqueo@ice.dhs.org"],
    ["David Conner", "David.Conner@ice.dhs.org"],
    ["Rachel Ali", "Rachel.Ali@ice.dhs.org"],
    ["Kat Danziger", "Kat.Danziger@ice.dhs.org"],
    ["Malissa Tucker", "Malissa.Tucker@ice.dhs.org"],
    ["Kathy French", "Kathy.French@ice.dhs.org"],
    ["Edward Kirksey", "Edward.Kirksey@ice.dhs.org"],
    ["Ian Jones-Muñiz", "Ian.Jones-Muñiz@ice.dhs.org"],
    ["Jordan Jordan Reddish", "Jordan.Jordan.Reddish@ice.dhs.org"],
    ["Lucien Lobban", "Lucien.Lobban@ice.dhs.org"],
    ["Alexandra Villadonga", "Alexandra.Villadonga@ice.dhs.org"],
    ["Timothy Pitner", "Timothy.Pitner@ice.dhs.org"],
    ["Silvia Ibarra", "Silvia.Ibarra@ice.dhs.org"],
    ["Yury Roberts", "Yury.Roberts@ice.dhs.org"],
    ["Adam Jovanovic", "Adam.Jovanovic@ice.dhs.org"],
    ["Tim Kelly", "Tim.Kelly@ice.dhs.org"],
    ["Steve Gray", "Steve.Gray@ice.dhs.org"],
    ["Daithra Mendoza", "Daithra.Mendoza@ice.dhs.org"],
    ["Cassandra Davis", "Cassandra.Davis@ice.dhs.org"],
    ["Brandon Ficklin", "Brandon.Ficklin@ice.dhs.org"],
    ["Ron Johnson", "Ron.Johnson@ice.dhs.org"],
    ["Tasha Wang", "Tasha.Wang@ice.dhs.org"],
    ["Caroline Moore", "Caroline.Moore@ice.dhs.org"],
    ["Vanessa Molina-Council", "Vanessa.Molina-Council@ice.dhs.org"],
    ["Deborah Robey", "Deborah.Robey@ice.dhs.org"],
    ["John H.", "John.H@ice.dhs.org"],
    ["Robert Davis", "Robert.Davis@ice.dhs.org"],
    ["Clay Martin", "Clay.Martin@ice.dhs.org"],
    ["Warren Hughley", "Warren.Hughley@ice.dhs.org"],
    ["Jayshree Reddy", "Jayshree.Reddy@ice.dhs.org"],
    ["Esteban Garcia", "Esteban.Garcia@ice.dhs.org"],
    ["Carlos Moreno", "Carlos.Moreno@ice.dhs.org"],
    ["Patrice Cureton", "Patrice.Cureton@ice.dhs.org"],
    ["alexandra Boraas", "alexandra.Boraas@ice.dhs.org"],
    ["Verlee Vallente", "Verlee.Vallente@ice.dhs.org"],
    ["Melly Kordus", "Melly.Kordus@ice.dhs.org"],
    ["Pedro Andino", "Pedro.Andino@ice.dhs.org"],
    ["Dantonio Fowler", "Dantonio.Fowler@ice.dhs.org"],
    ["Calvin Woolard", "Calvin.Woolard@ice.dhs.org"],
    ["andy helfinger", "andy.helfinger@ice.dhs.org"],
    ["Raul Romero-Ureña", "Raul.Romero-Ureña@ice.dhs.org"],
    ["norman Bradley", "norman.Bradley@ice.dhs.org"],
    ["Krystal Norton", "Krystal.Norton@ice.dhs.org"],
    ["Stephanie Hammond", "Stephanie.Hammond@ice.dhs.org"],
    ["Jill Bhalakia", "Jill.Bhalakia@ice.dhs.org"],
    ["James Graulich", "James.Graulich@ice.dhs.org"],
    ["Jonathan H. Yu", "Jonathan.H.Yu@ice.dhs.org"],
    ["Christina Bui", "Christina.Bui@ice.dhs.org"],
    ["Mark Murphy", "Mark.Murphy@ice.dhs.org"],
    ["Sam Kim", "Sam.Kim@ice.dhs.org"],
    ["Katie Pull", "Katie.Pull@ice.dhs.org"],
    ["Theresa Sullivan", "Theresa.Sullivan@ice.dhs.org"],
    ["Shantal D. Sparks", "Shantal.D.Sparks@ice.dhs.org"],
    ["Sean Patrick", "Sean.Patrick@ice.dhs.org"],
    ["Jason Pope", "Jason.Pope@ice.dhs.org"],
    ["Robert Davis", "Robert.Davis@ice.dhs.org"],
    ["Ian Fiske", "Ian.Fiske@ice.dhs.org"],
    ["Kelly Hyland", "Kelly.Hyland@ice.dhs.org"],
    ["Philip Villeneuve", "Philip.Villeneuve@ice.dhs.org"],
    ["Sabrina Thanse", "Sabrina.Thanse@ice.dhs.org"],
    ["Pamela Ataii", "Pamela.Ataii@ice.dhs.org"],
    ["Christine Kim, Esq.", "Christine.Kim@ice.dhs.org"],
    ["Jonathan Tabacoff", "Jonathan.Tabacoff@ice.dhs.org"],
    ["Carolyn Abdenour", "Carolyn.Abdenour@ice.dhs.org"],
    ["Philip Curtis", "Philip.Curtis@ice.dhs.org"],
    ["Christina Marquez, Esq.", "Christina.Marquez@ice.dhs.org"],
    ["Jonathan Needle", "Jonathan.Needle@ice.dhs.org"],
    ["Kishore Khan", "Kishore.Khan@ice.dhs.org"],
    ["Natalie Salvaggio", "Natalie.Salvaggio@ice.dhs.org"],
    ["Neha Rao", "Neha.Rao@ice.dhs.org"],
    ["Katheryn Rizzo", "Katheryn.Rizzo@ice.dhs.org"],
    ["Michelle Messina Yates", "Michelle.Messina.Yates@ice.dhs.org"],
    ["Gretchen Weiss", "Gretchen.Weiss@ice.dhs.org"],
    ["Erin Keeley", "Erin.Keeley@ice.dhs.org"],
    ["Cassandra Maximous", "Cassandra.Maximous@ice.dhs.org"],
    ["Kelly Kantor", "Kelly.Kantor@ice.dhs.org"],
    ["Alexandra Heavner", "Alexandra.Heavner@ice.dhs.org"],
    ["Allison Ballinger", "Allison.Ballinger@ice.dhs.org"],
    ["Nicholas Bolzman", "Nicholas.Bolzman@ice.dhs.org"],
    ["Lisa Kepple", "Lisa.Kepple@ice.dhs.org"],
    ["Kelly A. Foster", "Kelly.A.Foster@ice.dhs.org"],
    ["DONNA FLANAGAN", "DONNA.FLANAGAN@ice.dhs.org"],
    ["Nicole Dwyer", "Nicole.Dwyer@ice.dhs.org"],
    ["Kathleen Baugh", "Kathleen.Baugh@ice.dhs.org"],
    ["Jeffery Knybel", "Jeffery.Knybel@ice.dhs.org"],
    ["Hussein K. Saad", "Hussein.K.Saad@ice.dhs.org"],
    ["Claudia Ochoa", "Claudia.Ochoa@ice.dhs.org"],
    ["Cristobal Carreon", "Cristobal.Carreon@ice.dhs.org"],
    ["Lance Lueck, CFCI", "Lance.Lueck@ice.dhs.org"],
    ["Jody Prescott", "Jody.Prescott@ice.dhs.org"],
    ["Buck Rocker", "Buck.Rocker@ice.dhs.org"],
    ["Rachel Feuerhammer", "Rachel.Feuerhammer@ice.dhs.org"],
    ["Lincoln Jalelian", "Lincoln.Jalelian@ice.dhs.org"],
    ["Jack Spencer", "Jack.Spencer@ice.dhs.org"],
    ["Mary-Ellen Walter", "Mary-Ellen.Walter@ice.dhs.org"],
    ["Ahisha Alexander, MSM", "Ahisha.Alexander@ice.dhs.org"],
    ["Rebecca Fantauzzi", "Rebecca.Fantauzzi@ice.dhs.org"],
    ["Howard Charles", "Howard.Charles@ice.dhs.org"],
    ["Alma Vanessa Montenegro", "Alma.Vanessa.Montenegro@ice.dhs.org"],
    ["Ryan Matsuno", "Ryan.Matsuno@ice.dhs.org"],
    ["Michelle L. Brooks", "Michelle.L.Brooks@ice.dhs.org"],
    ["Shereen Herbert", "Shereen.Herbert@ice.dhs.org"],
    ["Domenic C.", "Domenic.C@ice.dhs.org"],
    ["Ankush Joshi", "Ankush.Joshi@ice.dhs.org"],
    ["Bryan Foltz", "Bryan.Foltz@ice.dhs.org"],
    ["Mario Foster", "Mario.Foster@ice.dhs.org"],
    ["Michael Watson", "Michael.Watson@ice.dhs.org"],
    ["Catherine Blaise Metcalf", "Catherine.Blaise.Metcalf@ice.dhs.org"],
    ["Patricia Nayor", "Patricia.Nayor@ice.dhs.org"],
    ["Paul Woo Hoogenstyn", "Paul.Woo.Hoogenstyn@ice.dhs.org"],
    ["Missy Garza", "Missy.Garza@ice.dhs.org"],
    ["Jessica M.", "Jessica.M@ice.dhs.org"],
    ["Kathy Trim", "Kathy.Trim@ice.dhs.org"],
    ["Veronica Bell", "Veronica.Bell@ice.dhs.org"],
    ["Aaron Murray", "Aaron.Murray@ice.dhs.org"],
    ["Joshua Chadwick", "Joshua.Chadwick@ice.dhs.org"],
    ["Frances Green", "Frances.Green@ice.dhs.org"],
    ["Todd Bachinski", "Todd.Bachinski@ice.dhs.org"],
    ["manuel ramirez", "manuel.ramirez@ice.dhs.org"],
    ["Michael Cherry", "Michael.Cherry@ice.dhs.org"],
    ["Eric Alexander", "Eric.Alexander@ice.dhs.org"],
    ["Maribel Padilla", "Maribel.Padilla@ice.dhs.org"],
    ["Joshua Jackson", "Joshua.Jackson@ice.dhs.org"],
    ["Immigration Group LLC", "Immigration.Group.LLC@ice.dhs.org"],
    ["Gizelle Rodriguez", "Gizelle.Rodriguez@ice.dhs.org"],
    ["Margaret Shea", "Margaret.Shea@ice.dhs.org"],
    ["Danielle H. Garten", "Danielle.H.Garten@ice.dhs.org"],
    ["Raizza K. Ty", "Raizza.K.Ty@ice.dhs.org"],
    ["Martin Williams", "Martin.Williams@ice.dhs.org"],
    ["Elizabeth Dewar", "Elizabeth.Dewar@ice.dhs.org"],
    ["Cynthia McGee", "Cynthia.McGee@ice.dhs.org"],
    ["Jessica Wallace", "Jessica.Wallace@ice.dhs.org"],
    ["Michael Webster", "Michael.Webster@ice.dhs.org"],
    ["Femon Padmore", "Femon.Padmore@ice.dhs.org"],
    ["Kent Stejskal", "Kent.Stejskal@ice.dhs.org"],
    ["Sienna Haslup", "Sienna.Haslup@ice.dhs.org"],
    ["Jonathan Markowsky", "Jonathan.Markowsky@ice.dhs.org"],
    ["Laura Bortnick", "Laura.Bortnick@ice.dhs.org"],
    ["Serena Voss", "Serena.Voss@ice.dhs.org"],
    ["Ken Clark", "Ken.Clark@ice.dhs.org"],
    ["Pat Elliott", "Pat.Elliott@ice.dhs.org"],
    ["Daniel Reilly, Jr.  PMP", "Daniel.Reilly@ice.dhs.org"],
    ["Jennifer Longmeyer-Wood", "Jennifer.Longmeyer-Wood@ice.dhs.org"],
    ["Eric Feldman", "Eric.Feldman@ice.dhs.org"],
    ["Anthony Scandiffio", "Anthony.Scandiffio@ice.dhs.org"],
    ["Steve Stow", "Steve.Stow@ice.dhs.org"],
    ["Robert Bartolo", "Robert.Bartolo@ice.dhs.org"],
    [
      "VINNETT RILEY-BAPTISTE MSHIA",
      "VINNETT.RILEY-BAPTISTE.MSHIA@ice.dhs.org"
    ],
    ["Cori W. Bassett", "Cori.W.Bassett@ice.dhs.org"],
    ["Timothy B. Worley", "Timothy.B.Worley@ice.dhs.org"],
    ["Jordan Christian Brough", "Jordan.Christian.Brough@ice.dhs.org"],
    ["gary mead", "gary.mead@ice.dhs.org"],
    ["Maureen Gallen", "Maureen.Gallen@ice.dhs.org"],
    ["Harold Cates", "Harold.Cates@ice.dhs.org"],
    ["Fernando Pineiro", "Fernando.Pineiro@ice.dhs.org"],
    ["Koransky Michael", "Koransky.Michael@ice.dhs.org"],
    ["Andrea La", "Andrea.La@ice.dhs.org"],
    ["Shannon Ely", "Shannon.Ely@ice.dhs.org"],
    ["Jake Nelson", "Jake.Nelson@ice.dhs.org"],
    ["Carl S.", "Carl.S@ice.dhs.org"],
    ["Michael Johnson", "Michael.Johnson@ice.dhs.org"],
    ["Sean Curran", "Sean.Curran@ice.dhs.org"],
    ["Clemente Hinojosa", "Clemente.Hinojosa@ice.dhs.org"],
    ["John Carlson", "John.Carlson@ice.dhs.org"],
    ["Emerson Toledo", "Emerson.Toledo@ice.dhs.org"],
    ["Gwendetta Gilchrist", "Gwendetta.Gilchrist@ice.dhs.org"],
    ["Yanique Brown", "Yanique.Brown@ice.dhs.org"],
    ["Katie Gray", "Katie.Gray@ice.dhs.org"],
    ["Ed Bennett", "Ed.Bennett@ice.dhs.org"],
    ["Nicole Spruill", "Nicole.Spruill@ice.dhs.org"],
    ["Tommy Mulhern", "Tommy.Mulhern@ice.dhs.org"],
    ["Patricia Baldovich", "Patricia.Baldovich@ice.dhs.org"],
    ["Paul Osterhaus", "Paul.Osterhaus@ice.dhs.org"],
    ["Elizabeth James", "Elizabeth.James@ice.dhs.org"],
    ["Phillip Buyas", "Phillip.Buyas@ice.dhs.org"],
    ["Marie Tedpahogo", "Marie.Tedpahogo@ice.dhs.org"],
    ["Dobson P", "Dobson.P@ice.dhs.org"],
    ["Suong Vong", "Suong.Vong@ice.dhs.org"],
    ["Barbara Gonzalez", "Barbara.Gonzalez@ice.dhs.org"],
    ["Thomas E. Feeley", "Thomas.E.Feeley@ice.dhs.org"],
    ["Patricia Cogswell", "Patricia.Cogswell@ice.dhs.org"],
    ["Nimisha Agarwal", "Nimisha.Agarwal@ice.dhs.org"],
    ["Jovonia Goetz", "Jovonia.Goetz@ice.dhs.org"],
    ["Corey Price", "Corey.Price@ice.dhs.org"],
    ["Alex A. Thornton", "Alex.A.Thornton@ice.dhs.org"],
    ["Jeremy Baker", "Jeremy.Baker@ice.dhs.org"],
    ["David Patrick", "David.Patrick@ice.dhs.org"],
    ["Karen Floyd", "Karen.Floyd@ice.dhs.org"],
    ["Tom Blank", "Tom.Blank@ice.dhs.org"],
    ["Leslie Saucedo", "Leslie.Saucedo@ice.dhs.org"],
    ["Gaines Robinson", "Gaines.Robinson@ice.dhs.org"],
    ["Melanie Denkins", "Melanie.Denkins@ice.dhs.org"],
    ["Tori Martinez", "Tori.Martinez@ice.dhs.org"],
    ["Rick Meier", "Rick.Meier@ice.dhs.org"],
    ["Christopher Burrow", "Christopher.Burrow@ice.dhs.org"],
    ["Matthew Guardiola, MA", "Matthew.Guardiola@ice.dhs.org"],
    ["David Evans", "David.Evans@ice.dhs.org"],
    ["Kelvin Carpenter", "Kelvin.Carpenter@ice.dhs.org"],
    ["Gary Dedios", "Gary.Dedios@ice.dhs.org"],
    ["Richard Ortiz", "Richard.Ortiz@ice.dhs.org"],
    ["John Taing", "John.Taing@ice.dhs.org"],
    ["Harold Hurtt", "Harold.Hurtt@ice.dhs.org"],
    ["Edwin Roman", "Edwin.Roman@ice.dhs.org"],
    ["Jason Bennett", "Jason.Bennett@ice.dhs.org"],
    ["Scott Lanum", "Scott.Lanum@ice.dhs.org"],
    ["Sean Hackbarth", "Sean.Hackbarth@ice.dhs.org"],
    ["Bryan D.", "Bryan.D@ice.dhs.org"],
    ["Jewoo Kim", "Jewoo.Kim@ice.dhs.org"],
    ["David Potvin", "David.Potvin@ice.dhs.org"],
    ["Mark Lawyer", "Mark.Lawyer@ice.dhs.org"],
    ["Albert C. Wright III, MBA", "Albert.C.Wright.III@ice.dhs.org"],
    ["Andrew Christie", "Andrew.Christie@ice.dhs.org"],
    ["sheena singh", "sheena.singh@ice.dhs.org"],
    ["Thomas Pailliotet", "Thomas.Pailliotet@ice.dhs.org"],
    ["Tita Aning Sahagun", "Tita.Aning.Sahagun@ice.dhs.org"],
    ["Denise DeJesus", "Denise.DeJesus@ice.dhs.org"],
    ["Emerald Nunez, MBA", "Emerald.Nunez@ice.dhs.org"],
    ["Belinda Minick", "Belinda.Minick@ice.dhs.org"],
    ["Tondalaya Hawkins", "Tondalaya.Hawkins@ice.dhs.org"],
    ["Wendy Clarity", "Wendy.Clarity@ice.dhs.org"],
    ["Jessica Cabell", "Jessica.Cabell@ice.dhs.org"],
    ["Patricia Washlick", "Patricia.Washlick@ice.dhs.org"],
    ["Gwendetta Gilchrist", "Gwendetta.Gilchrist@ice.dhs.org"],
    ["Joe Semyone", "Joe.Semyone@ice.dhs.org"],
    ["Vinny Hoy", "Vinny.Hoy@ice.dhs.org"],
    ["Monica DeRozario", "Monica.DeRozario@ice.dhs.org"],
    ["Val Tate", "Val.Tate@ice.dhs.org"],
    [
      "MohdTahirAbdRahman MohdTahir",
      "MohdTahirAbdRahman.MohdTahir@ice.dhs.org"
    ],
    ["Shandawn Grider", "Shandawn.Grider@ice.dhs.org"],
    ["marie baumann", "marie.baumann@ice.dhs.org"],
    ["Bruce Taylor", "Bruce.Taylor@ice.dhs.org"],
    ["kyeyune rodney", "kyeyune.rodney@ice.dhs.org"],
    ["Brandon Montgomery", "Brandon.Montgomery@ice.dhs.org"],
    ["Domenic Ionta", "Domenic.Ionta@ice.dhs.org"],
    ["Sabrina Gray", "Sabrina.Gray@ice.dhs.org"],
    ["Roxanna Rodriguez-Torres", "Roxanna.Rodriguez-Torres@ice.dhs.org"],
    ["Jeremy Mishler", "Jeremy.Mishler@ice.dhs.org"],
    ["Chris Moman", "Chris.Moman@ice.dhs.org"],
    ["Vincent G.", "Vincent.G@ice.dhs.org"],
    ["Mark Atchley", "Mark.Atchley@ice.dhs.org"],
    ["Marlen Pineiro", "Marlen.Pineiro@ice.dhs.org"],
    ["Frank L.", "Frank.L@ice.dhs.org"],
    ["Dontrell Smith", "Dontrell.Smith@ice.dhs.org"],
    ["Kevin Brown", "Kevin.Brown@ice.dhs.org"],
    ["HILLARY FLEMING", "HILLARY.FLEMING@ice.dhs.org"],
    ["Vincent Bowen", "Vincent.Bowen@ice.dhs.org"],
    ["Dawn Kutob", "Dawn.Kutob@ice.dhs.org"],
    ["Kimberly Chunn", "Kimberly.Chunn@ice.dhs.org"],
    ["Robert Walters", "Robert.Walters@ice.dhs.org"],
    ["James Luong", "James.Luong@ice.dhs.org"],
    ["Alan Todd Cheney", "Alan.Todd.Cheney@ice.dhs.org"],
    ["Jelani Scott", "Jelani.Scott@ice.dhs.org"],
    ["Joan DiMartino", "Joan.DiMartino@ice.dhs.org"],
    ["Rebecca Underwood", "Rebecca.Underwood@ice.dhs.org"],
    ["Joshua Hailey", "Joshua.Hailey@ice.dhs.org"],
    ["Theresa Bertucci", "Theresa.Bertucci@ice.dhs.org"],
    ["Aprell J.", "Aprell.J@ice.dhs.org"],
    ["Charles Garland", "Charles.Garland@ice.dhs.org"],
    ["Charles Curry", "Charles.Curry@ice.dhs.org"],
    ["Beth Cappello", "Beth.Cappello@ice.dhs.org"],
    ["Michelle Escobar, CIPP&#x2F;US", "Michelle.Escobar@ice.dhs.org"],
    ["Thomas Homan", "Thomas.Homan@ice.dhs.org"],
    ["Kenneth Bailey", "Kenneth.Bailey@ice.dhs.org"],
    ["Norman Parrish", "Norman.Parrish@ice.dhs.org"],
    ["Peter Edge", "Peter.Edge@ice.dhs.org"],
    ["Kevin Langdon", "Kevin.Langdon@ice.dhs.org"],
    ["Rodney Gregory", "Rodney.Gregory@ice.dhs.org"],
    ["William Ramey", "William.Ramey@ice.dhs.org"],
    ["Ricky Corum", "Ricky.Corum@ice.dhs.org"],
    ["Sumesh Karivelil", "Sumesh.Karivelil@ice.dhs.org"],
    ["Steve Acton", "Steve.Acton@ice.dhs.org"],
    ["Matthew Albence", "Matthew.Albence@ice.dhs.org"],
    ["Michael Conlon", "Michael.Conlon@ice.dhs.org"],
    ["James C. Harris III, MBA", "James.C.Harris.III@ice.dhs.org"],
    ["Maureen Gallen", "Maureen.Gallen@ice.dhs.org"],
    ["Scott Kirby", "Scott.Kirby@ice.dhs.org"],
    ["Jason Mitchell", "Jason.Mitchell@ice.dhs.org"],
    ["Alison Walder", "Alison.Walder@ice.dhs.org"],
    ["Keith Maly", "Keith.Maly@ice.dhs.org"],
    ["Ben Shih", "Ben.Shih@ice.dhs.org"],
    ["Chris Maiwurm", "Chris.Maiwurm@ice.dhs.org"],
    ["Shreena Lyons", "Shreena.Lyons@ice.dhs.org"],
    ["Elliott Harbin", "Elliott.Harbin@ice.dhs.org"],
    ["John Collick", "John.Collick@ice.dhs.org"],
    ["Michael Arnold", "Michael.Arnold@ice.dhs.org"],
    ["Jack Bonner", "Jack.Bonner@ice.dhs.org"],
    ["Thomas Finley", "Thomas.Finley@ice.dhs.org"],
    ["Dean Hagadorn", "Dean.Hagadorn@ice.dhs.org"],
    ["Cynthia Echeverria", "Cynthia.Echeverria@ice.dhs.org"],
    ["Ronald Craft", "Ronald.Craft@ice.dhs.org"],
    ["Lynece Edwards", "Lynece.Edwards@ice.dhs.org"],
    ["Maria Vega", "Maria.Vega@ice.dhs.org"],
    ["Martha Alem", "Martha.Alem@ice.dhs.org"],
    ["Mark Gromadzki", "Mark.Gromadzki@ice.dhs.org"],
    ["Vantreese Collins-Hodges", "Vantreese.Collins-Hodges@ice.dhs.org"],
    ["Vernon Weibel", "Vernon.Weibel@ice.dhs.org"],
    ["Ken Middleton", "Ken.Middleton@ice.dhs.org"],
    ["David Kazimierczak", "David.Kazimierczak@ice.dhs.org"],
    ["Lewis Baker", "Lewis.Baker@ice.dhs.org"],
    ["Tiffany McNeill", "Tiffany.McNeill@ice.dhs.org"],
    ["Ben Samuel", "Ben.Samuel@ice.dhs.org"],
    ["Tom Webb", "Tom.Webb@ice.dhs.org"],
    ["Jason Chilton", "Jason.Chilton@ice.dhs.org"],
    ["Winnie McDermott", "Winnie.McDermott@ice.dhs.org"],
    ["Austin Moore", "Austin.Moore@ice.dhs.org"],
    ["eileen falzini", "eileen.falzini@ice.dhs.org"],
    ["Wilson Hopkins", "Wilson.Hopkins@ice.dhs.org"],
    ["Lori deVenoge", "Lori.deVenoge@ice.dhs.org"],
    ["Dale Jepson", "Dale.Jepson@ice.dhs.org"],
    ["Scott Lanum", "Scott.Lanum@ice.dhs.org"],
    ["Jere Miles", "Jere.Miles@ice.dhs.org"],
    ["sadruddin abuwi", "sadruddin.abuwi@ice.dhs.org"],
    ["Leslie Alexander", "Leslie.Alexander@ice.dhs.org"],
    ["Lawan Jackson", "Lawan.Jackson@ice.dhs.org"],
    ["Judy.Thomas Judy.Thomas", "JudyThomas.Judy.Thomas@ice.dhs.org"],
    ["Tony Putnam", "Tony.Putnam@ice.dhs.org"],
    ["Darlene Davis", "Darlene.Davis@ice.dhs.org"],
    ["大红大紫", "大红大紫@ice.dhs.org"],
    ["Thomas Willoughby", "Thomas.Willoughby@ice.dhs.org"],
    ["Ryan Broadwater", "Ryan.Broadwater@ice.dhs.org"],
    ["Jerusalem T. Howard, Ph.D.", "Jerusalem.T.Howard@ice.dhs.org"],
    ["James Joseph", "James.Joseph@ice.dhs.org"],
    ["Debra Holborow Williams", "Debra.Holborow.Williams@ice.dhs.org"],
    ["Jessica K.", "Jessica.K@ice.dhs.org"],
    ["Sarah Todd, CFCM", "Sarah.Todd@ice.dhs.org"],
    ["Natasha Tyler", "Natasha.Tyler@ice.dhs.org"],
    ["Chris Lee", "Chris.Lee@ice.dhs.org"],
    ["Joseph Hale", "Joseph.Hale@ice.dhs.org"],
    ["Tiffany Smith-Ramiro", "Tiffany.Smith-Ramiro@ice.dhs.org"],
    ["Laurie Weeks", "Laurie.Weeks@ice.dhs.org"],
    ["Philip Quigley", "Philip.Quigley@ice.dhs.org"],
    ["Jamar Hudson", "Jamar.Hudson@ice.dhs.org"],
    ["Joel Lukens", "Joel.Lukens@ice.dhs.org"],
    ["Ken F.", "Ken.F@ice.dhs.org"],
    ["Jeramy Silfies", "Jeramy.Silfies@ice.dhs.org"],
    ["Stacie D. Jones", "Stacie.D.Jones@ice.dhs.org"],
    ["Tonya Stuber", "Tonya.Stuber@ice.dhs.org"],
    ["William Chin", "William.Chin@ice.dhs.org"],
    ["Barry Kobe", "Barry.Kobe@ice.dhs.org"],
    ["Jim Porter", "Jim.Porter@ice.dhs.org"],
    ["Lisa Vignerot, PMP, ACP", "Lisa.Vignerot@ice.dhs.org"],
    ["Alex Baden", "Alex.Baden@ice.dhs.org"],
    ["Steve La Rocca", "Steve.La.Rocca@ice.dhs.org"],
    ["Muhaimeinul Khan, PMP, CSM", "Muhaimeinul.Khan@ice.dhs.org"],
    ["Man T.", "Man.T@ice.dhs.org"],
    ["Duane M. Tushoski", "Duane.M.Tushoski@ice.dhs.org"],
    ["Anna Richardson", "Anna.Richardson@ice.dhs.org"],
    ["Ann Balough", "Ann.Balough@ice.dhs.org"],
    ["Christopher Wallace", "Christopher.Wallace@ice.dhs.org"],
    ["Erin Mundzahasic", "Erin.Mundzahasic@ice.dhs.org"],
    ["Karyn Becker", "Karyn.Becker@ice.dhs.org"],
    ["Kamillah Connolly", "Kamillah.Connolly@ice.dhs.org"],
    ["Omar K. Azero", "Omar.K.Azero@ice.dhs.org"],
    ["Timothy Gibney", "Timothy.Gibney@ice.dhs.org"],
    ["Gary Kastorf", "Gary.Kastorf@ice.dhs.org"],
    ["Gil Tucker", "Gil.Tucker@ice.dhs.org"],
    ["Kojo Danso", "Kojo.Danso@ice.dhs.org"],
    ["Michael Pikus Reid", "Michael.Pikus.Reid@ice.dhs.org"],
    ["Stephen Hall", "Stephen.Hall@ice.dhs.org"],
    ["Christy Mason", "Christy.Mason@ice.dhs.org"],
    ["Mabeline Hall", "Mabeline.Hall@ice.dhs.org"],
    ["Amos Desjardins", "Amos.Desjardins@ice.dhs.org"],
    ["Heather Sykes", "Heather.Sykes@ice.dhs.org"],
    ["Charles Cook Jr", "Charles.Cook.Jr@ice.dhs.org"],
    ["Aaron Justice", "Aaron.Justice@ice.dhs.org"],
    ["Shaneka Jones", "Shaneka.Jones@ice.dhs.org"],
    ["Cecilia Ripperger", "Cecilia.Ripperger@ice.dhs.org"],
    ["Sean Stephens", "Sean.Stephens@ice.dhs.org"],
    ["Veral Wright", "Veral.Wright@ice.dhs.org"],
    ["Lisa McRae", "Lisa.McRae@ice.dhs.org"],
    ["Thomas McCabe", "Thomas.McCabe@ice.dhs.org"],
    ["Mark Jackson", "Mark.Jackson@ice.dhs.org"],
    ["Nicole Larrain", "Nicole.Larrain@ice.dhs.org"],
    ["Tonya Sullivan", "Tonya.Sullivan@ice.dhs.org"],
    ["Sara Burns", "Sara.Burns@ice.dhs.org"],
    ["Lisa McRae", "Lisa.McRae@ice.dhs.org"],
    ["mdsaiful alam", "mdsaiful.alam@ice.dhs.org"],
    ["Crystal H.", "Crystal.H@ice.dhs.org"],
    ["Mickey Witchuwong", "Mickey.Witchuwong@ice.dhs.org"],
    ["Nathalie Lummert", "Nathalie.Lummert@ice.dhs.org"],
    ["Scott Steward", "Scott.Steward@ice.dhs.org"],
    ["Anthony J. Schlim", "Anthony.J.Schlim@ice.dhs.org"],
    ["Jaxon Sheriff-Parker", "Jaxon.Sheriff-Parker@ice.dhs.org"],
    ["Cindy M. Gripper", "Cindy.M.Gripper@ice.dhs.org"],
    ["Jesse L. Storey III", "Jesse.L.Storey.III@ice.dhs.org"],
    ["Antonia Acevedo", "Antonia.Acevedo@ice.dhs.org"],
    ["Charles. Cook", "Charles.Cook@ice.dhs.org"],
    ["Rosa M.", "Rosa.M@ice.dhs.org"],
    ["Brittany Elliott", "Brittany.Elliott@ice.dhs.org"],
    ["Ryan T. Howe", "Ryan.T.Howe@ice.dhs.org"],
    ["Rob Lombardi", "Rob.Lombardi@ice.dhs.org"],
    ["Katie Bay", "Katie.Bay@ice.dhs.org"],
    ["David E.", "David.E@ice.dhs.org"],
    ["Dawn Daggett", "Dawn.Daggett@ice.dhs.org"],
    ["Staci Leake", "Staci.Leake@ice.dhs.org"],
    ["Thomas Dale Carter, SPSS (Ret.)", "Thomas.Dale.Carter@ice.dhs.org"],
    ["Neeta Bajwa", "Neeta.Bajwa@ice.dhs.org"],
    ["Akil Baldwin", "Akil.Baldwin@ice.dhs.org"],
    ["Michael Williams", "Michael.Williams@ice.dhs.org"],
    ["Cursten Knott", "Cursten.Knott@ice.dhs.org"],
    ["Barry Harsa", "Barry.Harsa@ice.dhs.org"],
    ["Anthony Gomez", "Anthony.Gomez@ice.dhs.org"],
    ["Wayne Baker", "Wayne.Baker@ice.dhs.org"],
    ["Michael Mitchell", "Michael.Mitchell@ice.dhs.org"],
    ["Christopher Cady", "Christopher.Cady@ice.dhs.org"],
    ["David P.", "David.P@ice.dhs.org"],
    ["Farrah Rajabi", "Farrah.Rajabi@ice.dhs.org"],
    ["ALEXIS MULERO", "ALEXIS.MULERO@ice.dhs.org"],
    ["Andrew Healey", "Andrew.Healey@ice.dhs.org"],
    ["Fernando Plascencia", "Fernando.Plascencia@ice.dhs.org"],
    ["Lydell Butler", "Lydell.Butler@ice.dhs.org"],
    ["Joseph Daniels IV", "Joseph.Daniels.IV@ice.dhs.org"],
    ["Alisha J. Earle", "Alisha.J.Earle@ice.dhs.org"],
    ["Rich Boronyak", "Rich.Boronyak@ice.dhs.org"],
    ["Cynthia Ayres", "Cynthia.Ayres@ice.dhs.org"],
    ["Javier Ortiz", "Javier.Ortiz@ice.dhs.org"],
    ["David Fisher", "David.Fisher@ice.dhs.org"],
    ["Lonnie Brasby", "Lonnie.Brasby@ice.dhs.org"],
    ["Anthony Gomez", "Anthony.Gomez@ice.dhs.org"],
    ["Ralph Bradley", "Ralph.Bradley@ice.dhs.org"],
    ["Gay Debbie", "Gay.Debbie@ice.dhs.org"],
    ["Robert T Martinez", "Robert.T.Martinez@ice.dhs.org"],
    ["glenn spindel", "glenn.spindel@ice.dhs.org"],
    ["Smith M", "Smith.M@ice.dhs.org"],
    ["Cynthia Simmons", "Cynthia.Simmons@ice.dhs.org"],
    ["Lorena Prieto", "Lorena.Prieto@ice.dhs.org"],
    ["Kevin Williams", "Kevin.Williams@ice.dhs.org"],
    ["Hilary Seleb", "Hilary.Seleb@ice.dhs.org"],
    ["Sarah Silveira", "Sarah.Silveira@ice.dhs.org"],
    ["Manda Walters", "Manda.Walters@ice.dhs.org"],
    ["John Mohan", "John.Mohan@ice.dhs.org"],
    ["Carolyn Arorash", "Carolyn.Arorash@ice.dhs.org"],
    ["Michael C. Brown", "Michael.C.Brown@ice.dhs.org"],
    ["David Larrimore", "David.Larrimore@ice.dhs.org"],
    ["Rich Clark", "Rich.Clark@ice.dhs.org"],
    ["Scott Galloway", "Scott.Galloway@ice.dhs.org"],
    ["Scott Bowman", "Scott.Bowman@ice.dhs.org"],
    ["Kelly Stewart", "Kelly.Stewart@ice.dhs.org"],
    ["Mona Wadhwa", "Mona.Wadhwa@ice.dhs.org"],
    ["Irfan Malik", "Irfan.Malik@ice.dhs.org"],
    ["Lyn Rahilly", "Lyn.Rahilly@ice.dhs.org"],
    ["Charles Bily", "Charles.Bily@ice.dhs.org"],
    ["Eliza Dizon", "Eliza.Dizon@ice.dhs.org"],
    ["Curtis Crawford", "Curtis.Crawford@ice.dhs.org"],
    ["George Estes", "George.Estes@ice.dhs.org"],
    ["Roger Miranda", "Roger.Miranda@ice.dhs.org"],
    ["Amber Smith", "Amber.Smith@ice.dhs.org"],
    ["Josh Shleien", "Josh.Shleien@ice.dhs.org"],
    ["Laura Pluta", "Laura.Pluta@ice.dhs.org"],
    ["Brandon Andrathy", "Brandon.Andrathy@ice.dhs.org"],
    ["Chris Hoffmeister", "Chris.Hoffmeister@ice.dhs.org"],
    ["Gordon Li", "Gordon.Li@ice.dhs.org"],
    ["Hung Nguyen", "Hung.Nguyen@ice.dhs.org"],
    ["Klay D Lato", "Klay.D.Lato@ice.dhs.org"],
    ["Joseph Garner", "Joseph.Garner@ice.dhs.org"],
    ["Justin Bruno", "Justin.Bruno@ice.dhs.org"],
    ["Bill Richard", "Bill.Richard@ice.dhs.org"],
    ["Serrano Carlos", "Serrano.Carlos@ice.dhs.org"],
    ["DeVerah Bridges", "DeVerah.Bridges@ice.dhs.org"],
    ["Michael Proppe", "Michael.Proppe@ice.dhs.org"],
    ["Charles N. Harris", "Charles.N.Harris@ice.dhs.org"],
    ["Elijah Spencer", "Elijah.Spencer@ice.dhs.org"],
    ["Shannon Lally", "Shannon.Lally@ice.dhs.org"],
    ["David Mangoba", "David.Mangoba@ice.dhs.org"],
    ["Reshma Chaudhuri", "Reshma.Chaudhuri@ice.dhs.org"],
    ["Steve Gigel", "Steve.Gigel@ice.dhs.org"],
    ["Moroni Williams", "Moroni.Williams@ice.dhs.org"],
    ["Tanmay B.", "Tanmay.B@ice.dhs.org"],
    ["Peter Lee", "Peter.Lee@ice.dhs.org"],
    ["Gregory Davis", "Gregory.Davis@ice.dhs.org"],
    ["Steven Gabriel", "Steven.Gabriel@ice.dhs.org"],
    ["Debbie Miller", "Debbie.Miller@ice.dhs.org"],
    ["Majid Didehban", "Majid.Didehban@ice.dhs.org"],
    ["Andre Shurn", "Andre.Shurn@ice.dhs.org"],
    ["Rick Inzunza", "Rick.Inzunza@ice.dhs.org"],
    ["Beverly Minor", "Beverly.Minor@ice.dhs.org"],
    ["Dion Dixon", "Dion.Dixon@ice.dhs.org"],
    ["Steven Kata", "Steven.Kata@ice.dhs.org"],
    ["Jeff Oakes", "Jeff.Oakes@ice.dhs.org"],
    ["Carlos Serrano", "Carlos.Serrano@ice.dhs.org"],
    ["Bob Park", "Bob.Park@ice.dhs.org"],
    ["Jeffrey Brown", "Jeffrey.Brown@ice.dhs.org"],
    ["Chris F.", "Chris.F@ice.dhs.org"],
    ["Stephen Gonzalez", "Stephen.Gonzalez@ice.dhs.org"],
    ["Robert Gulley", "Robert.Gulley@ice.dhs.org"],
    ["Robert Neill", "Robert.Neill@ice.dhs.org"],
    ["Jose Vargas", "Jose.Vargas@ice.dhs.org"],
    ["Eric Delgado", "Eric.Delgado@ice.dhs.org"],
    ["魏翼展", "魏翼展@ice.dhs.org"],
    ["Keyona Fox", "Keyona.Fox@ice.dhs.org"],
    ["Taneshia McGuire", "Taneshia.McGuire@ice.dhs.org"],
    ["Emanuel Parker, M.B.A, M.S.ID", "Emanuel.Parker@ice.dhs.org"],
    ["Francisco Ramos", "Francisco.Ramos@ice.dhs.org"],
    ["Putnam, Anthony", "Putnam@ice.dhs.org"],
    ["Meir Braunstein", "Meir.Braunstein@ice.dhs.org"],
    ["Shelby Mikulec", "Shelby.Mikulec@ice.dhs.org"],
    ["Kevin Kerns", "Kevin.Kerns@ice.dhs.org"],
    ["Peggy Gaethke", "Peggy.Gaethke@ice.dhs.org"],
    ["Shannon Barnes", "Shannon.Barnes@ice.dhs.org"],
    ["Edward Ingram III", "Edward.Ingram.III@ice.dhs.org"],
    ["John Sanker", "John.Sanker@ice.dhs.org"],
    ["Susan Koonin", "Susan.Koonin@ice.dhs.org"],
    ["Jonathon Alcantara", "Jonathon.Alcantara@ice.dhs.org"],
    ["Lena Kim", "Lena.Kim@ice.dhs.org"],
    ["Christine Ward", "Christine.Ward@ice.dhs.org"],
    ["Allan Parks", "Allan.Parks@ice.dhs.org"],
    ["Pamela Viteri-Fitzmaurice", "Pamela.Viteri-Fitzmaurice@ice.dhs.org"],
    ["Reginald Irby", "Reginald.Irby@ice.dhs.org"],
    ["Robyn Luchau", "Robyn.Luchau@ice.dhs.org"],
    ["Bryan Hill", "Bryan.Hill@ice.dhs.org"],
    ["Jeremy Davis", "Jeremy.Davis@ice.dhs.org"],
    ["Ken Kroll", "Ken.Kroll@ice.dhs.org"],
    ["Kevin Nguyen", "Kevin.Nguyen@ice.dhs.org"],
    ["Travis Lennon", "Travis.Lennon@ice.dhs.org"],
    ["Danny Alonso", "Danny.Alonso@ice.dhs.org"],
    ["Louise Hewey", "Louise.Hewey@ice.dhs.org"],
    ["Reynaldo Carrejo", "Reynaldo.Carrejo@ice.dhs.org"],
    ["Mark Tipton", "Mark.Tipton@ice.dhs.org"],
    ["Valarie Sheppard", "Valarie.Sheppard@ice.dhs.org"],
    ["Megan Taylor", "Megan.Taylor@ice.dhs.org"],
    ["Jeffrey Choi", "Jeffrey.Choi@ice.dhs.org"],
    ["Sandra Crellin", "Sandra.Crellin@ice.dhs.org"],
    ["Sherry Laster", "Sherry.Laster@ice.dhs.org"],
    ["Olivia Hope Hunter", "Olivia.Hope.Hunter@ice.dhs.org"],
    ["Gugliuzza P", "Gugliuzza.P@ice.dhs.org"],
    ["Jack Bonner", "Jack.Bonner@ice.dhs.org"],
    ["Theresa Perez", "Theresa.Perez@ice.dhs.org"],
    ["Marcia Joseph", "Marcia.Joseph@ice.dhs.org"],
    ["reginald irby", "reginald.irby@ice.dhs.org"],
    ["Hejin Scott", "Hejin.Scott@ice.dhs.org"],
    ["Jeffrey Sealey", "Jeffrey.Sealey@ice.dhs.org"],
    ["Edward J Daly", "Edward.J.Daly@ice.dhs.org"],
    ["Robert Turner", "Robert.Turner@ice.dhs.org"],
    ["Elena Kepper", "Elena.Kepper@ice.dhs.org"],
    ["Kyle Ruchalski", "Kyle.Ruchalski@ice.dhs.org"],
    ["Dov Kawamoto", "Dov.Kawamoto@ice.dhs.org"],
    ["David Hoover", "David.Hoover@ice.dhs.org"],
    ["Ernest Chambers", "Ernest.Chambers@ice.dhs.org"],
    ["Oliver Francisco", "Oliver.Francisco@ice.dhs.org"],
    ["Chris Cecere", "Chris.Cecere@ice.dhs.org"],
    ["Mark McGlinchey", "Mark.McGlinchey@ice.dhs.org"],
    ["Erik S.", "Erik.S@ice.dhs.org"],
    ["Brian Stiles", "Brian.Stiles@ice.dhs.org"],
    ["Mary Smith", "Mary.Smith@ice.dhs.org"],
    ["Todd Bachinski", "Todd.Bachinski@ice.dhs.org"],
    ["Christy Young", "Christy.Young@ice.dhs.org"],
    ["Matthew S. Ferraro", "Matthew.S.Ferraro@ice.dhs.org"],
    ["Max Triveline", "Max.Triveline@ice.dhs.org"],
    ["Craig Sumner", "Craig.Sumner@ice.dhs.org"],
    ["Katrina Tasby", "Katrina.Tasby@ice.dhs.org"],
    ["Daniel Niesman", "Daniel.Niesman@ice.dhs.org"],
    ["Brishauna Hawkins-Wesson", "Brishauna.Hawkins-Wesson@ice.dhs.org"],
    ["Eric Bergstrom", "Eric.Bergstrom@ice.dhs.org"],
    ["Melanie Jones", "Melanie.Jones@ice.dhs.org"],
    ["Mosi McCrary", "Mosi.McCrary@ice.dhs.org"],
    ["Lugenia Ricks", "Lugenia.Ricks@ice.dhs.org"],
    ["Ashley Mendibles", "Ashley.Mendibles@ice.dhs.org"],
    ["Hoai-An Tran", "Hoai-An.Tran@ice.dhs.org"],
    ["Carol Gordon, MBA, PhD", "Carol.Gordon@ice.dhs.org"],
    ["Nikkia Taylor", "Nikkia.Taylor@ice.dhs.org"],
    ["Jen Levi", "Jen.Levi@ice.dhs.org"],
    ["John Laing", "John.Laing@ice.dhs.org"],
    ["Belinda Eller", "Belinda.Eller@ice.dhs.org"],
    ["Leo Atienza", "Leo.Atienza@ice.dhs.org"],
    ["Dina Gates", "Dina.Gates@ice.dhs.org"],
    ["New Carol Edwards", "New.Carol.Edwards@ice.dhs.org"],
    ["Bernie Lalime-Brown", "Bernie.Lalime-Brown@ice.dhs.org"],
    ["Shayla Chisholm", "Shayla.Chisholm@ice.dhs.org"],
    ["Cheryl D Lewis", "Cheryl.D.Lewis@ice.dhs.org"],
    ["Nathaly Gaffke", "Nathaly.Gaffke@ice.dhs.org"],
    ["John Laing", "John.Laing@ice.dhs.org"],
    ["Latoya Reese, MBA", "Latoya.Reese@ice.dhs.org"],
    ["Shaun Moss", "Shaun.Moss@ice.dhs.org"],
    ["Tom Wise", "Tom.Wise@ice.dhs.org"],
    ["Dorothy Jones", "Dorothy.Jones@ice.dhs.org"],
    ["Charlene Lovell", "Charlene.Lovell@ice.dhs.org"],
    ["Mary Gibbs", "Mary.Gibbs@ice.dhs.org"],
    ["Kristy Mc Dowell", "Kristy.Mc.Dowell@ice.dhs.org"],
    ["Mom Work", "Mom.Work@ice.dhs.org"],
    ["Nicholas Maravich", "Nicholas.Maravich@ice.dhs.org"],
    ["Rachel Ross", "Rachel.Ross@ice.dhs.org"],
    ["Scott Weber", "Scott.Weber@ice.dhs.org"],
    ["John Sherrill", "John.Sherrill@ice.dhs.org"],
    ["John Dam", "John.Dam@ice.dhs.org"],
    ["Rosemary Gonzalez", "Rosemary.Gonzalez@ice.dhs.org"],
    ["Sharon Baker", "Sharon.Baker@ice.dhs.org"],
    ["Donna Forget", "Donna.Forget@ice.dhs.org"],
    ["Jenny Mellon", "Jenny.Mellon@ice.dhs.org"],
    ["Bret Evins", "Bret.Evins@ice.dhs.org"],
    ["gwenn reed", "gwenn.reed@ice.dhs.org"],
    ["Leila Mukai", "Leila.Mukai@ice.dhs.org"],
    ["Steven Davis", "Steven.Davis@ice.dhs.org"],
    ["Alberto Flores", "Alberto.Flores@ice.dhs.org"],
    ["Francis Capdevila", "Francis.Capdevila@ice.dhs.org"],
    ["Roy Schoolcraft", "Roy.Schoolcraft@ice.dhs.org"],
    ["Kayla Morose", "Kayla.Morose@ice.dhs.org"],
    ["Jacqueline Barsamian", "Jacqueline.Barsamian@ice.dhs.org"],
    ["Scott Freni", "Scott.Freni@ice.dhs.org"],
    ["Christopher Ortega", "Christopher.Ortega@ice.dhs.org"],
    ["Shayne Palmer", "Shayne.Palmer@ice.dhs.org"],
    ["Tyler Oliveira", "Tyler.Oliveira@ice.dhs.org"],
    ["Jaylen Johnson", "Jaylen.Johnson@ice.dhs.org"],
    ["Katherine Porter-Waldrip", "Katherine.Porter-Waldrip@ice.dhs.org"],
    ["Ramleekanchau Ramlee", "Ramleekanchau.Ramlee@ice.dhs.org"],
    ["Natasha Wise", "Natasha.Wise@ice.dhs.org"],
    ["andrew williams", "andrew.williams@ice.dhs.org"],
    ["Kris Randolph", "Kris.Randolph@ice.dhs.org"],
    ["Ronald Dorman", "Ronald.Dorman@ice.dhs.org"],
    ["Kaylan S.", "Kaylan.S@ice.dhs.org"],
    ["Kevin Leo Traynor", "Kevin.Leo.Traynor@ice.dhs.org"],
    ["Kelly Lowery", "Kelly.Lowery@ice.dhs.org"],
    ["Orlando Threadgill M.Ed Ed.S", "Orlando.Threadgill.MEd.Ed.S@ice.dhs.org"],
    ["Breanne Wise", "Breanne.Wise@ice.dhs.org"],
    ["Luis Iturriaga", "Luis.Iturriaga@ice.dhs.org"],
    ["Damian Davey", "Damian.Davey@ice.dhs.org"],
    ["Lowell Johnson", "Lowell.Johnson@ice.dhs.org"],
    ["Harold Hicks", "Harold.Hicks@ice.dhs.org"],
    ["Justin Poe", "Justin.Poe@ice.dhs.org"],
    ["Erica Cooper", "Erica.Cooper@ice.dhs.org"],
    ["Blake Zorn", "Blake.Zorn@ice.dhs.org"],
    ["Maurice Lee", "Maurice.Lee@ice.dhs.org"],
    ["Lindley Maloy", "Lindley.Maloy@ice.dhs.org"],
    ["Stephen Golden", "Stephen.Golden@ice.dhs.org"],
    ["Matisha Montgomery", "Matisha.Montgomery@ice.dhs.org"],
    ["Rico Lindsey", "Rico.Lindsey@ice.dhs.org"],
    ["Kathleen Doyle", "Kathleen.Doyle@ice.dhs.org"],
    ["Emily Puhl", "Emily.Puhl@ice.dhs.org"],
    ["James Coleman", "James.Coleman@ice.dhs.org"],
    ["drissa photographe événe-", "drissa.photographe.événe-@ice.dhs.org"],
    ["Erica N. Williams, MPA", "Erica.N.Williams@ice.dhs.org"],
    ["Geoff Harriman", "Geoff.Harriman@ice.dhs.org"],
    ["Lauren Berkebile, CIPM", "Lauren.Berkebile@ice.dhs.org"],
    ["Michael Mullican", "Michael.Mullican@ice.dhs.org"],
    ["Guillermo Marti", "Guillermo.Marti@ice.dhs.org"],
    ["William Wilson", "William.Wilson@ice.dhs.org"],
    ["Caitlin Shimer Soper", "Caitlin.Shimer.Soper@ice.dhs.org"],
    ["An Nguyen", "An.Nguyen@ice.dhs.org"],
    ["mullai rajasekaran", "mullai.rajasekaran@ice.dhs.org"],
    ["Hillary LaRose", "Hillary.LaRose@ice.dhs.org"],
    ["chad miller", "chad.miller@ice.dhs.org"],
    ["Anthony Callender", "Anthony.Callender@ice.dhs.org"],
    ["Rachel Walker", "Rachel.Walker@ice.dhs.org"],
    ["Chris Winters", "Chris.Winters@ice.dhs.org"],
    ["Sara Cheeseman", "Sara.Cheeseman@ice.dhs.org"],
    ["Jeaniae Lawton", "Jeaniae.Lawton@ice.dhs.org"],
    ["Fabian Molina", "Fabian.Molina@ice.dhs.org"],
    ["Trevor Morgan", "Trevor.Morgan@ice.dhs.org"],
    ["Pedro Rios", "Pedro.Rios@ice.dhs.org"],
    ["Lisa Padilla", "Lisa.Padilla@ice.dhs.org"],
    ["Albert Soto", "Albert.Soto@ice.dhs.org"],
    ["Robert Gulley", "Robert.Gulley@ice.dhs.org"],
    ["Felipe Torres", "Felipe.Torres@ice.dhs.org"],
    ["Shuiab Ahmed", "Shuiab.Ahmed@ice.dhs.org"],
    ["Dakota McMurray, PharmD, MPH, BCPS", "Dakota.McMurray@ice.dhs.org"],
    ["Julie Carter", "Julie.Carter@ice.dhs.org"],
    ["Angela Silva", "Angela.Silva@ice.dhs.org"],
    ["Wesley Derrick", "Wesley.Derrick@ice.dhs.org"],
    ["Gail Montenegro", "Gail.Montenegro@ice.dhs.org"],
    ["John Challis", "John.Challis@ice.dhs.org"],
    ["Erika Breaux", "Erika.Breaux@ice.dhs.org"],
    ["Glenn McCormack, CPA", "Glenn.McCormack@ice.dhs.org"],
    ["Edwin Lun", "Edwin.Lun@ice.dhs.org"],
    ["Clayton Washington", "Clayton.Washington@ice.dhs.org"],
    ["Celia Garcia", "Celia.Garcia@ice.dhs.org"],
    ["Rachel Monnot", "Rachel.Monnot@ice.dhs.org"],
    ["Brett Dehm", "Brett.Dehm@ice.dhs.org"],
    ["Melissa Shanahan", "Melissa.Shanahan@ice.dhs.org"],
    ["Sergio Braun", "Sergio.Braun@ice.dhs.org"],
    ["Steven Rush", "Steven.Rush@ice.dhs.org"],
    ["Travis Wessler", "Travis.Wessler@ice.dhs.org"],
    ["DeLaney Dickinson", "DeLaney.Dickinson@ice.dhs.org"],
    ["Angela Valero", "Angela.Valero@ice.dhs.org"],
    ["Matt Elliston", "Matt.Elliston@ice.dhs.org"],
    ["Kirt Temple", "Kirt.Temple@ice.dhs.org"],
    ["James Kurtessis", "James.Kurtessis@ice.dhs.org"],
    ["Khaalid Walls", "Khaalid.Walls@ice.dhs.org"],
    ["Dennis Cunningham", "Dennis.Cunningham@ice.dhs.org"],
    ["James Lee", "James.Lee@ice.dhs.org"],
    ["Matthew Wilchek", "Matthew.Wilchek@ice.dhs.org"],
    ["Brett Borntrager", "Brett.Borntrager@ice.dhs.org"],
    ["Hamid Shah", "Hamid.Shah@ice.dhs.org"],
    ["isabella Moritz", "isabella.Moritz@ice.dhs.org"],
    ["Z Dimitri", "Z.Dimitri@ice.dhs.org"],
    ["victor rodriguez", "victor.rodriguez@ice.dhs.org"],
    ["Blanca Rios", "Blanca.Rios@ice.dhs.org"],
    ["Jorge Hidalgo", "Jorge.Hidalgo@ice.dhs.org"],
    ["Rachel Simon", "Rachel.Simon@ice.dhs.org"],
    ["Amy Delauter", "Amy.Delauter@ice.dhs.org"],
    ["Sunita Subedi", "Sunita.Subedi@ice.dhs.org"],
    ["Gwendolyn Eveline", "Gwendolyn.Eveline@ice.dhs.org"],
    ["Carolyn Leary", "Carolyn.Leary@ice.dhs.org"],
    ["Judith P. Fai", "Judith.P.Fai@ice.dhs.org"],
    [
      "Winston R. Churchill Canady, PHR, MBA, MSHRM",
      "Winston.R.Churchill.Canady@ice.dhs.org"
    ],
    ["James Brown", "James.Brown@ice.dhs.org"],
    ["Pierce A", "Pierce.A@ice.dhs.org"],
    ["Regina George", "Regina.George@ice.dhs.org"],
    ["Rosaula Dacumos, NP-C", "Rosaula.Dacumos@ice.dhs.org"],
    ["Charlene Miles", "Charlene.Miles@ice.dhs.org"],
    ["Shauna Burnett", "Shauna.Burnett@ice.dhs.org"],
    ["Nancy Emmi", "Nancy.Emmi@ice.dhs.org"],
    ["Charlene Miles", "Charlene.Miles@ice.dhs.org"],
    ["Joe Rosipal", "Joe.Rosipal@ice.dhs.org"],
    ["Dean Boyd", "Dean.Boyd@ice.dhs.org"],
    ["Patrick Conklin", "Patrick.Conklin@ice.dhs.org"],
    ["Mom Mom", "Mom.Mom@ice.dhs.org"],
    ["Wendy Berg", "Wendy.Berg@ice.dhs.org"],
    ["Carissa Frasca Cutrell", "Carissa.Frasca.Cutrell@ice.dhs.org"],
    ["Mindy Watson", "Mindy.Watson@ice.dhs.org"],
    ["SunSearra Ruffin", "SunSearra.Ruffin@ice.dhs.org"],
    ["Leticia Zamarripa, ICE", "Leticia.Zamarripa@ice.dhs.org"],
    ["Harold Ort", "Harold.Ort@ice.dhs.org"],
    ["Derrick Roy", "Derrick.Roy@ice.dhs.org"],
    ["Suzanne Edmundson", "Suzanne.Edmundson@ice.dhs.org"],
    ["Sharon Largo", "Sharon.Largo@ice.dhs.org"],
    ["Becky Shoustal CPA, CGFM", "Becky.Shoustal.CPA@ice.dhs.org"],
    ["Elizabeth Williams", "Elizabeth.Williams@ice.dhs.org"],
    ["Robert Adame", "Robert.Adame@ice.dhs.org"],
    ["Megan Bailie", "Megan.Bailie@ice.dhs.org"],
    ["Jordan Holz", "Jordan.Holz@ice.dhs.org"],
    ["Jennifer D. Elzea", "Jennifer.D.Elzea@ice.dhs.org"],
    ["Tony Daly", "Tony.Daly@ice.dhs.org"],
    ["Rhanishia Smith, RN, MSN", "Rhanishia.Smith@ice.dhs.org"],
    ["Craig Hellmann", "Craig.Hellmann@ice.dhs.org"],
    ["Tyeshia J. Williams", "Tyeshia.J.Williams@ice.dhs.org"],
    ["Justine Whelan", "Justine.Whelan@ice.dhs.org"],
    ["Lori K. Haley", "Lori.K.Haley@ice.dhs.org"],
    ["Jesus A. Quilantan", "Jesus.A.Quilantan@ice.dhs.org"],
    ["Merechia Davis CDP", "Merechia.Davis.CDP@ice.dhs.org"],
    ["Alcinda Trotter", "Alcinda.Trotter@ice.dhs.org"],
    ["Gary F", "Gary.F@ice.dhs.org"],
    ["Reed Schuyler", "Reed.Schuyler@ice.dhs.org"],
    ["Jason Brokaw", "Jason.Brokaw@ice.dhs.org"],
    ["Marlon Bowles", "Marlon.Bowles@ice.dhs.org"],
    ["Perry Jones", "Perry.Jones@ice.dhs.org"],
    ["Pamela Peters", "Pamela.Peters@ice.dhs.org"],
    ["Robert Valancia", "Robert.Valancia@ice.dhs.org"],
    ["Teresa Klein", "Teresa.Klein@ice.dhs.org"],
    ["Paul Burkholtz", "Paul.Burkholtz@ice.dhs.org"],
    ["Aaron Montgomery", "Aaron.Montgomery@ice.dhs.org"],
    ["Edie Lederman", "Edie.Lederman@ice.dhs.org"],
    ["Robert Arnott", "Robert.Arnott@ice.dhs.org"],
    ["Priscilla Forrester", "Priscilla.Forrester@ice.dhs.org"],
    ["Sarah Rodriguez", "Sarah.Rodriguez@ice.dhs.org"],
    ["Elizabeth Johnson", "Elizabeth.Johnson@ice.dhs.org"],
    ["Kia Shoamotamedi", "Kia.Shoamotamedi@ice.dhs.org"],
    ["Jon Feere", "Jon.Feere@ice.dhs.org"],
    ["Michelle Ramsden, Esq. CIPP&#x2F;G", "Michelle.Ramsden@ice.dhs.org"],
    ["Brian Barrontine, MSOR, MSS, PMP", "Brian.Barrontine@ice.dhs.org"],
    ["Eric L.", "Eric.L@ice.dhs.org"],
    ["Matthew Bourke", "Matthew.Bourke@ice.dhs.org"],
    ["Aristides Moura", "Aristides.Moura@ice.dhs.org"],
    ["Karissa Marcum", "Karissa.Marcum@ice.dhs.org"],
    ["Luis Casanova", "Luis.Casanova@ice.dhs.org"],
    ["Tom Byrd", "Tom.Byrd@ice.dhs.org"],
    ["Casey Iwai, Psy.D.", "Casey.Iwai@ice.dhs.org"],
    ["Patrick L.", "Patrick.L@ice.dhs.org"],
    ["David Shoemaker", "David.Shoemaker@ice.dhs.org"],
    ["Dan Eagan, CPA, PMP, CGFM", "Dan.Eagan@ice.dhs.org"],
    ["Jeffrey Sanford", "Jeffrey.Sanford@ice.dhs.org"],
    ["Jordan Bell", "Jordan.Bell@ice.dhs.org"],
    ["Nestor Yglesias", "Nestor.Yglesias@ice.dhs.org"],
    ["Delinda Cockerham", "Delinda.Cockerham@ice.dhs.org"],
    ["Deborah Whitten", "Deborah.Whitten@ice.dhs.org"],
    ["Albert Quinones", "Albert.Quinones@ice.dhs.org"],
    ["Danisha Robbins", "Danisha.Robbins@ice.dhs.org"],
    ["Mary Grant", "Mary.Grant@ice.dhs.org"],
    ["Tammy Martin", "Tammy.Martin@ice.dhs.org"],
    ["Vincent Picard", "Vincent.Picard@ice.dhs.org"],
    ["John Meehan", "John.Meehan@ice.dhs.org"],
    ["carol Carol Parker", "carol.Carol.Parker@ice.dhs.org"],
    ["Stephanie Mros", "Stephanie.Mros@ice.dhs.org"],
    ["Norman Bradley", "Norman.Bradley@ice.dhs.org"],
    ["Joshua Langelier", "Joshua.Langelier@ice.dhs.org"],
    ["Timothy Brockman", "Timothy.Brockman@ice.dhs.org"],
    ["Robert Podgorni", "Robert.Podgorni@ice.dhs.org"],
    ["Carlos Tapia Jr", "Carlos.Tapia.Jr@ice.dhs.org"],
    ["James Hicks", "James.Hicks@ice.dhs.org"],
    ["Joniel Genesis", "Joniel.Genesis@ice.dhs.org"],
    ["Pankaj Garg", "Pankaj.Garg@ice.dhs.org"],
    ["Jocelyn Hicks", "Jocelyn.Hicks@ice.dhs.org"],
    ["Sue Evans Cirocco", "Sue.Evans.Cirocco@ice.dhs.org"],
    ["Tomas Navalo", "Tomas.Navalo@ice.dhs.org"],
    ["Manuel Avila", "Manuel.Avila@ice.dhs.org"],
    ["Mark Evrard PMP, ITIL", "Mark.Evrard.PMP@ice.dhs.org"],
    ["jennifer longmeyer-wood", "jennifer.longmeyer-wood@ice.dhs.org"],
    ["Charissa Pallas", "Charissa.Pallas@ice.dhs.org"],
    ["Bert Medina", "Bert.Medina@ice.dhs.org"],
    ["Ed Johnson", "Ed.Johnson@ice.dhs.org"],
    ["Stewart D. Smith, DHSc, MPH, MA, CCHP", "Stewart.D.Smith@ice.dhs.org"],
    ["Thomas Fraser", "Thomas.Fraser@ice.dhs.org"],
    ["Stephen Antkowiak, PMP", "Stephen.Antkowiak@ice.dhs.org"],
    ["Eric L Brown Sr, CPPM, CF", "Eric.L.Brown.Sr@ice.dhs.org"],
    ["Bryan Cox", "Bryan.Cox@ice.dhs.org"],
    ["Carlos Moreno", "Carlos.Moreno@ice.dhs.org"],
    ["Isabel Vázquez", "Isabel.Vázquez@ice.dhs.org"],
    ["Rosa Fisher", "Rosa.Fisher@ice.dhs.org"],
    ["Dennis Slate", "Dennis.Slate@ice.dhs.org"],
    ["Jason D.", "Jason.D@ice.dhs.org"],
    ["Nisha S.", "Nisha.S@ice.dhs.org"],
    ["Lance A. Washington", "Lance.A.Washington@ice.dhs.org"],
    ["Adrienne Coates", "Adrienne.Coates@ice.dhs.org"],
    ["Mai Whelan", "Mai.Whelan@ice.dhs.org"],
    ["Heidi Griggs", "Heidi.Griggs@ice.dhs.org"],
    ["David Long", "David.Long@ice.dhs.org"],
    ["Maria Loredo", "Maria.Loredo@ice.dhs.org"],
    ["Kirk Sheppard", "Kirk.Sheppard@ice.dhs.org"],
    ["Kobe D", "Kobe.D@ice.dhs.org"],
    ["Tammy Cyr", "Tammy.Cyr@ice.dhs.org"],
    ["Michele Fowler", "Michele.Fowler@ice.dhs.org"],
    ["Carlos Bracero", "Carlos.Bracero@ice.dhs.org"],
    ["Samuel Aquino", "Samuel.Aquino@ice.dhs.org"],
    ["Zamarripa Leticia", "Zamarripa.Leticia@ice.dhs.org"],
    ["jc Jc", "jc.Jc@ice.dhs.org"],
    ["Juan Soto", "Juan.Soto@ice.dhs.org"],
    ["Gilbert Garcia", "Gilbert.Garcia@ice.dhs.org"],
    ["Joel Garcia", "Joel.Garcia@ice.dhs.org"],
    ["Albert Olvera", "Albert.Olvera@ice.dhs.org"],
    ["raymond Al bazy", "raymond.Al.bazy@ice.dhs.org"],
    ["Jimmy Jones", "Jimmy.Jones@ice.dhs.org"],
    ["Kenji Smart", "Kenji.Smart@ice.dhs.org"],
    ["Lisa Stenson", "Lisa.Stenson@ice.dhs.org"],
    ["B Rod", "B.Rod@ice.dhs.org"],
    ["Francois Delisle", "Francois.Delisle@ice.dhs.org"]
  ]);

  var h1 = document.createElement("h4");
  var h2 = document.createElement("h4");
  var bcc = document.createElement("ul");
  var all = document.createElement("ul");

  h1.innerHTML = "Send emails in bulk (100 at a time - less personal).";
  h2.innerHTML =
    "Send emails individually (more personal because the name is included).";

  for (var i = 0, len = emails.length; i < len; i++) {
    var li = document.createElement("li");
    var a = document.createElement("a");
    const s = [];
    var fname = emails[i][0].split(" ")[0];

    s.push(
      "mailto:",
      emails[i][1],
      "?subject=",
      fname + ", " + subject,
      "&body=",
      bd2.replace("NAME", fname)
    );
    a.href = s.join("");
    a.innerHTML = "Send to " + emails[i][0];
    a.onclick = stat("individual", emails[i][1]);
    li.appendChild(a);
    all.appendChild(li);
  }

  var chunked = _.chunk(emails, 100);
  for (var i = 0, len = chunked.length; i < len; i++) {
    var li = document.createElement("li");
    var a = document.createElement("a");
    const s = [];
    const recipient = chunked[i].shift()[1];

    s.push(
      "mailto:",
      recipient,
      "?subject=",
      subject,
      "&bcc=",
      chunked[i]
        .map(function(a) {
          return a[1];
        })
        .join(","),
      "&body=",
      bd
    );
    a.href = s.join("");
    a.innerHTML = "Bulk Group " + (i + 1) + " (BCC'd)";
    a.onclick = stat("bulk-bcc", "Bulk Group " + (i + 1) + " (BCC'd)");
    li.appendChild(a);
    bcc.appendChild(li);
  }

  document.body.appendChild(h1);
  document.body.appendChild(bcc);
  document.body.appendChild(h2);
  document.body.appendChild(all);

  function stat(label, value) {
    return function() {
      if (ga) {
        ga("send", "email", label, value);
      }
    };
  }
})();
